### PR TITLE
ARROW-13594: [CI] Enable nightly turbodbc builds again

### PR DESCRIPTION
**Pull request by jorisvandenbossche**

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow submit test-conda-python-3.7-turbodbc-master test-conda-python-3.7-turbodbc-latest

**Comment by jorisvandenbossche** [comment]
The build is failing with 

```
 [154/156] Building CXX object cpp/turbodbc_arrow/Test/CMakeFiles/turbodbc_arrow_test.dir/tests/arrow_result_set_test.cpp.o
FAILED: cpp/turbodbc_arrow/Test/CMakeFiles/turbodbc_arrow_test.dir/tests/arrow_result_set_test.cpp.o 
/opt/conda/envs/arrow/bin/x86_64-conda-linux-gnu-c++  -I/turbodbc/cpp/turbodbc_arrow/Library -I/turbodbc/cpp/turbodbc_arrow/../cpp_odbc/Library -I/turbodbc/cpp/turbodbc_arrow/../turbodbc/Library -I/turbodbc/cpp/turbodbc_arrow/Test -isystem /opt/conda/envs/arrow/include/python3.7m -isystem /opt/conda/envs/arrow/lib/python3.7/site-packages/numpy/core/include -isystem /turbodbc/pybind11/include -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /opt/conda/envs/arrow/include -Wall -Wextra -g -O0 -pedantic   -std=c++11 -MD -MT cpp/turbodbc_arrow/Test/CMakeFiles/turbodbc_arrow_test.dir/tests/arrow_result_set_test.cpp.o -MF cpp/turbodbc_arrow/Test/CMakeFiles/turbodbc_arrow_test.dir/tests/arrow_result_set_test.cpp.o.d -o cpp/turbodbc_arrow/Test/CMakeFiles/turbodbc_arrow_test.dir/tests/arrow_result_set_test.cpp.o -c /turbodbc/cpp/turbodbc_arrow/Test/tests/arrow_result_set_test.cpp
/turbodbc/cpp/turbodbc_arrow/Test/tests/arrow_result_set_test.cpp: In member function 'std::shared_ptr<arrow::Array> ArrowResultSetTest::MakePrimitive(int64_t, int64_t)':
/turbodbc/cpp/turbodbc_arrow/Test/tests/arrow_result_set_test.cpp:119:48: error: 'arrow::BitUtil' has not been declared
  119 |             const int64_t null_nbytes = arrow::BitUtil::BytesForBits(length);
      |                                                ^~~~~~~
/turbodbc/cpp/turbodbc_arrow/Test/tests/arrow_result_set_test.cpp:127:24: error: 'arrow::BitUtil' has not been declared
  127 |                 arrow::BitUtil::ClearBit(null_bitmap->mutable_data(), i * (length / null_count));
      |                        ^~~~~~~
ninja: build stopped: subcommand failed.
1
```

I suppose this is caused by https://github.com/apache/arrow/pull/11792

Was `arrow::BitUtil` considered public API?

**Comment by alippai** [comment]
@jorisvandenbossche sorry for the premature issue close, I forgot about the arrow side tests :)

The failure is for the upcoming arrow 7.0.0, right?

**Comment by jorisvandenbossche** [comment]
Yes, the failure is caused by a change in arrow master, which will be in 7.0.0

**Comment by pitrou** [comment]
Hmm, turbodbc is supposed to have CI tests against nightly builds of Arrow, but they actually [download Arrow 6.0.1 from conda-forge](https://github.com/blue-yonder/turbodbc/runs/4684405922?check_suite_focus=true#step:5:380).

**Comment by xhochy** [comment]
@github-actions crossbow submit test-conda-python-3.7-turbodbc-master test-conda-python-3.7-turbodbc-latest

**Comment by xhochy** [comment]
@github-actions crossbow submit test-conda-python-3.7-turbodbc-master test-conda-python-3.7-turbodbc-latest

**Comment by xhochy** [comment]
@jorisvandenbossche I have rebased here and the tests are now all passing 💚

**Comment by jorisvandenbossche** [comment]
Cool, thanks!
