### ISSUE TITLE
Trouble compiling cython file when installing pyarrow

### ISSUE THREAD

**Issue by aniket-l** [apache/arrow#11581]
I am trying to install streamlit (which requires pyarrow as dependency) through Yocto and Bitbake.
For Pyarrow installation, I am getting cython compilation errors

PFA the Pyarrow bitbake recipe as well as the error logs (log.do_compile)
[error_logs.txt](https://github.com/apache/arrow/files/7452856/error_logs.txt)
[python3-pyarrow_5.0.0.txt](https://github.com/apache/arrow/files/7452872/python3-pyarrow_5.0.0.txt)

I am new to Cython as well as Yocto and don't understand the source of the errors. Would like some help with debugging the same. Any suggestions are welcome.

Thanks,
Aniket Limaye

**Comment by bkmgit** [comment]
Would version 6.0.0 work for you? https://pypi.org/project/pyarrow/ Does `pip3 install pyarrow` work on its own?

**Comment by aniket-l** [comment]
`pip3 install pyarrow` does seem to work but we want to enable pyarrow out of box on the target. We are using Yocto and bitbake to compile python packages for the target system. We want to fix this through the bitbake recipe itself but I don't know what the root cause of the errors is.

**Comment by bkmgit** [comment]
Ok. Found documentation for bitbake https://docs.yoctoproject.org/bitbake/index.html Do you have an example of a minimal failing recipe?

If you need to use Conda, perhaps try nightly build https://anaconda.org/arrow-nightlies/pyarrow

[Streamlit](https://streamlit.io) has a repository https://github.com/streamlit/streamlit - does this work for you on commonly available hardware? It seems you are building on aarch 64 - there are some CI tests for this. So probably your setup may need to be adapted to work correctly.

**Comment by aniket-l** [comment]
The txt file attached in the original post here is the recipe for pyarrow that is failing (python3-pyarrow_5.0.0.txt).

**Comment by westonpace** [comment]
Have you tried updating the cython version?  Do you know what version of cython you are using?

**Comment by aniket-l** [comment]
I am using version 0.29.14, which as I understand satisfies the requirement (>=0.29)
Could be a problem with the cython recipe as well? 
Attaching for reference: [cython_recipe.zip](https://github.com/apache/arrow/files/7517944/cython_recipe.zip)

**Comment by jorisvandenbossche** [comment]
@aniket-l sorry for the slow follow-up. Do you still have the issue, or were you able to fix it?
