### PR TITLE
GH-50987: [C++] Fix builds with the macOS 11.3 SDK

### LINKED ISSUE #50987: [C++] std::identity in bitmap_ops.cc breaks build with macOS 11.3 SDK
### Describe the bug, including details regarding any error messages, version, and platform.

(Written by Claude, message reviewed by @thisisnic before posting)

Since #50785 was merged, Arrow C++ fails to compile in the R macOS CRAN nightly (`test-r-macos-as-cran`, `cran-release` config):

https://github.com/ursacomputing/crossbow/actions/runs/32845953430/job/97795549784

```
cpp/src/arrow/util/bitmap_ops.cc:230:57: error: no template named 'identity' in namespace 'std'; did you mean '__identity'?
```

The same error appears at lines 307 and 323 (`MapBitmapUnary<std::identity>`):
https://github.com/apache/arrow/blob/577d3b9c4bd64ad1bdd12dcaaf115b88ac626e0e/cpp/src/arrow/util/bitmap_ops.cc#L230

This job builds against the macOS 11.3 SDK to match CRAN's macOS builder. The libc++ headers in that SDK predate `std::identity` (added in libc++ 12 / macOS 12 SDK), so it is unavailable even with `-std=gnu++20`. The `cran-m1` config, which uses the current Xcode SDK, passes.

This is the only use of `std::identity` in `cpp/src`, so replacing it with a local identity functor should be enough. Without a fix, the R package will fail to build on CRAN's macOS builder at the next release.

### Component(s)

C++

### PR DESCRIPTION
**Pull request by 1fanwang**
### Rationale for this change

The R macOS CRAN nightly stopped building Arrow C++ after #50785. It uses the macOS
11.3 SDK to match CRAN's builder, and fails on one file with "no template named
'identity' in namespace 'std'" at lines 230, 307 and 323. That SDK's libc++ predates
the standard identity functor, which arrived in libc++ 12 with the macOS 12 SDK, so
the name is absent whatever standard is selected. The cran-m1 job uses a current SDK
and passes, which is why only this builder is red.

Before this change the R package cannot be built on CRAN's macOS builder. After it,
the file compiles there.

Closes #50987.

### What changes are included in this PR?

That file is the only one in the C++ tree naming the missing symbol, at the three
sites above. It now uses a small equivalent functor in the same translation unit, so
the compile-time fast path that skips per-bit work still matches and the bitmap copy
keeps its memcpy shortcut. The bitwise-not functor is older and untouched. No
behavior or API change.

### Are these changes tested?

Reproduced on a real macOS 11.3 SDK, whose internal identity helper sits at the same
header line cited in the CI log, confirming the same libc++. From a checkout of this
branch:

```console
$ curl -fsSL https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX11.3.sdk.tar.xz | tar -xJ -C /tmp
$ SDK=/tmp/MacOSX11.3.sdk
$ F=cpp/src/arrow/util/bitmap_ops.cc
$ clang++ -std=gnu++20 -isysroot "$SDK" -I cpp/src -fsyntax-only "$F" && echo ok
ok
$ git checkout upstream/main -- "$F"
$ clang++ -std=gnu++20 -isysroot "$SDK" -I cpp/src -fsyntax-only "$F"
230:57: error: no template named 'identity' in namespace 'std'
307:23: error: no template named 'identity' in namespace 'std'
323:30: error: no template named 'identity' in namespace 'std'
6 errors generated.
```

Behavior is unchanged. The bit utility test target builds and its bitmap copy,
invert and reverse cases pass, covering both branches of the mapping helper: the
byte-aligned memcpy path and the bit-offset path that calls the functor.

```
[  PASSED  ] 4 tests.
```

The local run compiles the failing translation unit, not the full R build, which the
CRAN job here covers.

### Are there any user-facing changes?

No.

* GitHub Issue: #50987

### CODE REVIEW

**Comment by thisisnic** [comment]
@github-actions crossbow submit test-r-macos-as-cran

**Review by thisisnic — APPROVED** [review]
CI failures unrelated - cc @pitrou - is this OK to merge?

**Review by pitrou — APPROVED** [review]

**Comment by pitrou** [comment]
LGTM, thank you @thisisnic and @1fanwang
