### PR TITLE
ARROW-4689: [Go] Add support for wasm

### PR DESCRIPTION
**Pull request by sbinet**

### CODE REVIEW

**Comment by wesm** [comment]
Can you create a JIRA for this? Do you want to document how to compile under wasm?

**Comment by sbinet** [comment]
done: https://issues.apache.org/jira/browse/ARROW-4689

> Do you want to document how to compile under wasm?

I could... even though I am not completely sure where putting it would make the most sense...
putting it in the API documentation (ie: godoc.org) sounds funny to me.
any idea? @stuartcarnie ?

**Comment by wesm** [comment]
@sbinet we have just set up a project-level documentation project. At some point you should start to write some Go documentation 

https://github.com/apache/arrow/tree/master/docs/source

**Review by wesm — APPROVED** [review]
+1

**Comment by tschaub** [comment]
I don't see any documentation that might have come out of this, but I was guessing that something like this might work:
```
GOOS=js GOARCH=wasm go build -o test.wasm ./main.go
```

This fails for me with the following:
```
# github.com/apache/arrow/go/v9/internal/utils
../../go/pkg/mod/github.com/apache/arrow/go/v9@v9.0.0/internal/utils/transpose_ints_def.go:76:4: undefined: TransposeInt8Int8
../../go/pkg/mod/github.com/apache/arrow/go/v9@v9.0.0/internal/utils/transpose_ints_def.go:78:4: undefined: TransposeInt8Int16
../../go/pkg/mod/github.com/apache/arrow/go/v9@v9.0.0/internal/utils/transpose_ints_def.go:80:4: undefined: TransposeInt8Int32
../../go/pkg/mod/github.com/apache/arrow/go/v9@v9.0.0/internal/utils/transpose_ints_def.go:82:4: undefined: TransposeInt8Int64
../../go/pkg/mod/github.com/apache/arrow/go/v9@v9.0.0/internal/utils/transpose_ints_def.go:84:4: undefined: TransposeInt8Uint8
../../go/pkg/mod/github.com/apache/arrow/go/v9@v9.0.0/internal/utils/transpose_ints_def.go:86:4: undefined: TransposeInt8Uint16
../../go/pkg/mod/github.com/apache/arrow/go/v9@v9.0.0/internal/utils/transpose_ints_def.go:88:4: undefined: TransposeInt8Uint32
../../go/pkg/mod/github.com/apache/arrow/go/v9@v9.0.0/internal/utils/transpose_ints_def.go:90:4: undefined: TransposeInt8Uint64
../../go/pkg/mod/github.com/apache/arrow/go/v9@v9.0.0/internal/utils/transpose_ints_def.go:95:4: undefined: TransposeInt16Int8
../../go/pkg/mod/github.com/apache/arrow/go/v9@v9.0.0/internal/utils/transpose_ints_def.go:97:4: undefined: TransposeInt16Int16
../../go/pkg/mod/github.com/apache/arrow/go/v9@v9.0.0/internal/utils/transpose_ints_def.go:97:4: too many errors
# github.com/apache/thrift/lib/go/thrift
../../go/pkg/mod/github.com/apache/thrift@v0.15.0/lib/go/thrift/socket_unix_conn.go:60:63: undefined: syscall.MSG_PEEK
../../go/pkg/mod/github.com/apache/thrift@v0.15.0/lib/go/thrift/socket_unix_conn.go:60:80: undefined: syscall.MSG_DONTWAIT
```

I opened https://issues.apache.org/jira/browse/ARROW-17557 with this information, but thought I'd drop a comment here since it might help others that are struggling to do the same.

I'm curious if building with `GOOS=js GOARCH=wasm` supposed to be supported.

**Comment by kirillrdy** [comment]
try `GOOS=js GOARCH=wasm go build -tags noasm -o test.wasm ./main.go`

**Comment by tschaub** [comment]
Thanks for the suggestion.  I'm still seeing the `syscall` issues with `-tags noasm`.

```
GOOS=js GOARCH=wasm go build -tags noasm -o test.wasm ./main.go
# github.com/apache/thrift/lib/go/thrift
../../go/pkg/mod/github.com/apache/thrift@v0.15.0/lib/go/thrift/socket_unix_conn.go:60:63: undefined: syscall.MSG_PEEK
../../go/pkg/mod/github.com/apache/thrift@v0.15.0/lib/go/thrift/socket_unix_conn.go:60:80: undefined: syscall.MSG_DONTWAIT
```

I'll dig more later.

**Comment by zeroshade** [comment]
@tschaub Thanks, when you have the minimal example I'll take a look. It appears to be an issue specific with Thrift so I'll see if i can dig in there and see if there's a way to fix that syscall or otherwise.

**Comment by zeroshade** [comment]
@tschaub 

Aha, it looks like latest version of thrift (v0.16.0) fixed this issue and added a `!wasm` build tag to that file. The current development version of the parquet lib (v10) has already upgraded to that version of thrift. If you upgrade your local version of thrift (`go get -u github.com/apache/thrift@v0.16.0`) or if you upgrade your version of parquet and arrow to v10, you should be able to build with WASM without issue. Let me know if this works for you please.

**Comment by tschaub** [comment]
Thank you, @zeroshade.  The build works after updating to v10.  I'll update https://issues.apache.org/jira/browse/ARROW-17557.  I appreciate your help.
