### ISSUE TITLE
[Java] Make it run well with the netty newest version 4.1.96

### ISSUE THREAD

**Issue by panbingkun** [apache/arrow#36928]
### Describe the bug, including details regarding any error messages, version, and platform.

When I used `netty arrow memory 13.0.0` and `netty 4.1.96.Final` in Spark, the following error occurred,
Because `netty 4.1.96.Final` version has revert some modifications, in order to ensure that `netty arrow memory 13.0.0` works well with ``netty 4.1.96.Final`` version, I suggest making similar modifications here.
1.Compilation errors are as follows:
https://ci.appveyor.com/project/ApacheSoftwareFoundation/spark/builds/47657403
<img width="955" alt="image" src="https://github.com/apache/arrow/assets/15246973/e7ee2da9-97c0-474c-a62d-5821858e361f">

2.Some modifications have been reverted in `netty 4.1.96.Final` as follows:
<img width="884" alt="image" src="https://github.com/apache/arrow/assets/15246973/0226685a-cfa3-4b8b-b114-23ad8d027c05">
<img width="907" alt="image" src="https://github.com/apache/arrow/assets/15246973/a6ea21a0-8531-42b6-ab9d-25eaab1c7fde">
https://netty.io/news/2023/07/27/4-1-96-Final.html
https://github.com/netty/netty/pull/13510
 

### Component(s)

Java
