### PR TITLE
GH-26209: [Ruby] Add support for Ruby 2.5

### LINKED ISSUE #26209: [Ruby] ArrowTable::load test fails due to undefined method
### Describe the bug, including details regarding any error messages, version, and platform.

https://github.com/ursacomputing/crossbow/actions/runs/3822668197/jobs/6503035048#step:5:12051
`Error: test_filter(TestArrowTable::load): NoMethodError: undefined method `end_with?' for :set_inspect_n_fragments:Symbol`

Probably caused by #15148 
cc @kou 

### Component(s)

Ruby

### PR DESCRIPTION
**Pull request by kou**
# Which issue does this PR close?

Closes #26209

# Rationale for this change

Ruby 2.5 was EOL but Ubuntu 18.04 still uses Ruby 2.5. Note that Ubuntu 18.04 will reach EOL on 2023-04.

# What changes are included in this PR?

Ruby 2.5 compatible implementation and tests.

# Are these changes tested?

Yes

# Are there any user-facing changes?

No.

* Closes: #26209

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit verify-rc-source-ruby-*

**Comment by kou** [comment]
@github-actions crossbow submit verify-rc-source-ruby-*

**Comment by kou** [comment]
+1
