### ISSUE TITLE
[C++] Threads::Threads dependency is missing for static linking

### ISSUE THREAD

**Issue by kou** [apache/arrow#40432]
### Describe the bug, including details regarding any error messages, version, and platform.

This is caused by #39824.

example-cpp-minimal-build-static:

https://github.com/ursacomputing/crossbow/actions/runs/8210651831/job/22458477613#step:3:1523

```text
[100%] Linking CXX executable arrow-example
/usr/bin/ld: /usr/local/lib/libarrow.a(file.cc.o): in function `void std::lock<std::unique_lock<std::mutex>, std::unique_lock<std::mutex>>(std::unique_lock<std::mutex>&, std::unique_lock<std::mutex>&)':
file.cc:(.text._ZSt4lockISt11unique_lockISt5mutexES2_JEEvRT_RT0_DpRT1_[_ZSt4lockISt11unique_lockISt5mutexES2_JEEvRT_RT0_DpRT1_]+0x21): undefined reference to `pthread_mutex_trylock'
/usr/bin/ld: /usr/local/lib/libarrow.a(cancel.cc.o): in function `arrow::(anonymous namespace)::SignalStopState::RegisterHandlers(std::vector<int, std::allocator<int> > const&)':
cancel.cc:(.text+0x133e): undefined reference to `pthread_create'
...
```

### Component(s)

C++

**Comment by kou** [comment]
Issue resolved by pull request 40433
https://github.com/apache/arrow/pull/40433
