### PR TITLE
GH-50636: [C++] Replace std::span/ranges usage to fix macOS CRAN

### LINKED ISSUE #50636: [C++][R] macOS 11.3 SDK fails to compile std::span iterator range in vector_sort
### Describe the bug, including details regarding any error messages, version, and platform.

The `test-r-macos-as-cran` crossbow job fails when compiling `vector_sort.cc` against the macOS 11.3 SDK:

> error: cannot convert initializer list argument to 'std::span<uint64_t>'

This was introduced in #50248 https://github.com/apache/arrow/blob/bc9d1349e091dead2044ed200d3e3e867578b354/cpp/src/arrow/compute/kernels/vector_sort.cc#L234-L248

The macOS 11.3 libc++ implementation uses __wrap_iter for span iterators but only accepts raw pointers in this constructor. Using indices.data() for the internal range iteration, or constructing the range with subspan(), would likely retain the span interface and fix the issue.

```diff
 diff --git a/cpp/src/arrow/compute/kernels/vector_sort.cc b/cpp/src/arrow/compute/kernels/vector_sort.cc
-  auto range_start = indices.begin();
+  auto range_start = indices.data();
   auto range_cur = range_start;
+  const auto range_end = range_start + indices.size();
   auto last_value = GetView::LogicalValue(array.GetView(*range_cur - offset));
-  while (++range_cur != indices.end()) {
+  while (++range_cur != range_end) {
```

Crossbow failure:
https://github.com/ursacomputing/crossbow/actions/runs/30154135424/job/89669316217#step:9:2303

### Component(s)

C++, R

### PR DESCRIPTION
**Pull request by tadeja**
### Rationale for this change
Fix #50636 - `test-r-macos-as-cran` nightly job fails compiling `visit({range_start, range_cur})` introduced in #50248.
```console
/Users/runner/work/crossbow/crossbow/arrow/cpp/src/arrow/compute/kernels/vector_sort.cc:325:11: note: candidate function not viable: cannot convert initializer list argument to 'std::span<uint64_t>' (aka 'span<unsigned long long>')
  325 |           [&](std::span<uint64_t> indices) { SortNextColumn(indices, offset); });
```
The job pins [macOS SDK 11.3](https://github.com/ursacomputing/crossbow/actions/runs/30420027426/job/90474737457#step:9:14), so libc++ there does not have C++20 iterator-pair span constructor available yet ([available with libc++ 14](https://libcxx.llvm.org/Status/Cxx20.html)).
Similar problem as in recent #50295

### What changes are included in this PR?
Replace std::span iterator-pair constructor with subspan in `vector_sort.cc`
Also replace std::ranges in `parquet/arrow/reader.cc` introduced in #50271

### Are these changes tested?
Yes, builds locally and crossbow `test-r-macos-as-cran` job succeeds.

### Are there any user-facing changes?
No.
* GitHub Issue: #50636

### CODE REVIEW

**Comment by tadeja** [comment]
@github-actions crossbow submit test-r-macos-as-cran

**Comment by tadeja** [comment]
Now `vector_sort.cc` compiles successfully and fresh failing [`test-r-macos-as-cran` log](https://github.com/ursacomputing/crossbow/actions/runs/30450308864/job/90570515768#step:9:2228) points to this remaining newer failure
```console
[ 87%] Building CXX object src/parquet/CMakeFiles/parquet_objlib.dir/arrow/reader.cc.o
/Users/runner/work/crossbow/crossbow/arrow/cpp/src/parquet/arrow/reader.cc:735:46: error: no member named 'ranges' in namespace 'std'
  735 |       const auto first_invalid_offset = std::ranges::adjacent_find(
      |                                         ~~~~~^
/Users/runner/work/crossbow/crossbow/arrow/cpp/src/parquet/arrow/reader.cc:740:26: error: no member named 'ranges' in namespace 'std'
  740 |             start + std::ranges::distance(run_offsets.begin(), first_invalid_offset);
      |                     ~~~~~^
2 errors generated.
make[2]: *** [src/parquet/CMakeFiles/parquet_objlib.dir/arrow/reader.cc.o] Error 1
```

 from yesterday's #50271  `std::ranges::adjacent_find(` and `std::ranges::distance(run_offsets.begin(), first_invalid_offset);`
https://github.com/apache/arrow/pull/50271/changes#diff-6a73dc8ee650cf7b5b8a51f7d4f9f0197823416155c0de7de400294fea588f11R735-R740

**Comment by tadeja** [comment]
@github-actions crossbow submit test-r-macos-as-cran

**Comment by tadeja** [comment]
With fix in `vector_sort.cc` and in `parquet/arrow/reader.cc` now `test-r-macos-as-cran` job is finally passing:
https://github.com/ursacomputing/crossbow/actions/runs/30455196131/job/90586871066

**Comment by tadeja** [comment]
(I'll rebase for the four unrelated failing CI macOS checks after this is resolved: #50688 / #50712)

**Comment by tadeja** [comment]
cc @HuaHuaY and @taepper if you could also take a look at the changes here adjusting your recent PRs, that'd be very welcome!

File: cpp/src/arrow/compute/kernels/vector_sort.cc [hunk 1]
```diff
@@ -231,19 +231,19 @@ void VisitConstantRanges(const ArrayType& array, std::span<uint64_t> indices,
...
     if (v != last_value) {
-      visit({range_start, range_cur});
+      visit(indices.subspan(range_start, range_cur - range_start));
       range_start = range_cur;
       last_value = v;
     }
   }
   if (range_start != range_cur) {
-    visit({range_start, range_cur});
+    visit(indices.subspan(range_start, range_cur - range_start));
```
Comment (taepper) [inline cpp/src/arrow/compute/kernels/vector_sort.cc:246]: This looks very sensible. Good idea to revert to `size_t` entirely instead of recalculating (start, size) using iterator differences in the `subspan` calls!

Thank you, I was not aware of the portability problems re/ `std::span`!

**Comment by HuaHuaY** [comment]
> Now `vector_sort.cc` compiles successfully and fresh failing [`test-r-macos-as-cran` log](https://github.com/ursacomputing/crossbow/actions/runs/30450308864/job/90570515768#step:9:2228) points to this remaining newer failure

Sad. I didn't expect there are still some failing CI build. Thank you for your fix. I updated https://github.com/apache/arrow/issues/48587#issuecomment-3870744730 to document this.

**Review by kou — APPROVED** [review]
+1
