### PR TITLE
GH-36928: [Java] Make it run well with the netty newest version 4.1.96

### LINKED ISSUE #36928: [Java] Make it run well with the netty newest version 4.1.96
### Describe the bug, including details regarding any error messages, version, and platform.

When I used `netty arrow memory 13.0.0` and `netty 4.1.96.Final` in Spark, the following error occurred,
Because `netty 4.1.96.Final` version has revert some modifications, in order to ensure that `netty arrow memory 13.0.0` works well with ``netty 4.1.96.Final`` version, I suggest making similar modifications here.
1.Compilation errors are as follows:
https://ci.appveyor.com/project/ApacheSoftwareFoundation/spark/builds/47657403
image

2.Some modifications have been reverted in `netty 4.1.96.Final` as follows:
image
image
https://netty.io/news/2023/07/27/4-1-96-Final.html
https://github.com/netty/netty/pull/13510
 

### Component(s)

Java

### PR DESCRIPTION
**Pull request by panbingkun**
When I used `netty arrow memory 13.0.0` and `netty 4.1.96.Final` in Spark, the following error occurred,
Because `netty 4.1.96.Final` version has revert some modifications, in order to ensure that `netty arrow memory 13.0.0` works well with ``netty 4.1.96.Final`` version, I suggest making similar modifications here.
1.Compilation errors are as follows:
https://ci.appveyor.com/project/ApacheSoftwareFoundation/spark/builds/47657403
image

2.Some modifications have been reverted in `netty 4.1.96.Final` as follows:
image
image
https://netty.io/news/2023/07/27/4-1-96-Final.html
https://github.com/netty/netty/pull/13510
* Closes: #36928

### CODE REVIEW

**Comment by panbingkun** [comment]
When I used `netty arrow memory 13.0.0` and `netty 4.1.96.Final` in Spark, the following error occurred,
Because `netty 4.1.96.Final` version has revert some modifications, in order to ensure that `netty arrow memory 13.0.0` works well with ``netty 4.1.96.Final`` version, I suggest making similar modifications here.
1.Compilation errors are as follows:
https://ci.appveyor.com/project/ApacheSoftwareFoundation/spark/builds/47657403
image

2.Some modifications have been reverted in `netty 4.1.96.Final` as follows:
image
image
https://netty.io/news/2023/07/27/4-1-96-Final.html
https://github.com/netty/netty/pull/13510

**Review by lidavidm — APPROVED** [review]
Thank you for catching this! 

@raulcd since we don't have RC2 out yet, would it be possible to cherry-pick this too? It also apparently avoids a potential performance regression in Flight

**Comment by raulcd** [comment]
Sure! that sounds good to me!

**Comment by lidavidm** [comment]
Thanks Raúl! I added this to the 13.0.0 milestone, I'll go update the blog post too

**Comment by raulcd** [comment]
> I added this to the 13.0.0 milestone

cherry-picked to `maint-13.0.0`

**Comment by lidavidm** [comment]
@github-actions crossbow submit *spark*
