### ISSUE TITLE
[Ruby] ArrowTable::load test fails due to undefined method

### ISSUE THREAD

**Issue by assignUser** [apache/arrow#26209]
### Describe the bug, including details regarding any error messages, version, and platform.

https://github.com/ursacomputing/crossbow/actions/runs/3822668197/jobs/6503035048#step:5:12051
`Error: test_filter(TestArrowTable::load): NoMethodError: undefined method `end_with?' for :set_inspect_n_fragments:Symbol`

Probably caused by #15148 
cc @kou 

### Component(s)

Ruby

**Comment by kou** [comment]
Oh, sorry. I didn't notice it. I'll fix it soon.
