### PR TITLE
GH-45949: [R] Fix CRAN warnings for 19.0.1 about compiled code

### PR DESCRIPTION
**Pull request by jonkeane**
This gets rid of `OBJECT`, `DATAPTR` has been replaced with `INTEGER()`, `REAL()`, etc. though strings are more complicated. I will fully admit that this C++ is stretching my comfort zone, so might include obviously wrong things!

CI is currently failing, but I'm not totally sure yet if that means the code changes here are wrong or if maybe these allow us to have slightly different assumptions about materialization (see https://github.com/apache/arrow/pull/45951#discussion_r2019675135)

I've also requested reviews broadly for folks I know have been around this code before, I appreciate any effort that y'all can spare 🙏 

* GitHub Issue: #45949

### CODE REVIEW

File: r/src/altrep.cpp [hunk 1]
```diff
@@ -1267,24 +1304,27 @@ sexp test_arrow_altrep_copy_by_dataptr(sexp x) {
...
   } else if (TYPEOF(x) == STRSXP) {
     cpp11::writable::strings out(Rf_xlength(x));
-    SEXP* ptr = reinterpret_cast<SEXP*>(DATAPTR(x));
-    for (R_xlen_t i = 0; i < n; i++) {
-      out[i] = ptr[i];
+    R_xlen_t len = Rf_xlength(x);
+
+    for (R_xlen_t i = 0; i < len; i++) {
+      SEXP str_elt = reinterpret_cast<SEXP>(STRING_ELT(x, i));
+      out[i] = str_elt;
```
Comment (jonkeane) [inline r/src/altrep.cpp:1325]: Something about this isn't quite right, because the test here (and other assertions that strings are materialized) fail:

https://github.com/apache/arrow/blob/3c63f37d4211e7a8d42c8388a12888e63fe377e3/r/tests/testthat/test-altrep.R#L249

But I haven't yet figured out if this is a real problem with this code change, or maybe it's an assumption in the tests that no longer holds?

@nealrichardson @paleolimbot y'all might have thoughts ?

Comment (jonkeane) [reply r/src/altrep.cpp:1323]: As a follow-on for myself that line 1319 is duplicative and should be removed (but I don't want to outdate ^^^ just yet)

File: r/src/arrow_types.h [hunk 2]
```diff
@@ -173,14 +173,39 @@ template <typename RVector>
...
+    } else if (TYPEOF(vec) == STRSXP) {
+      cpp11::writable::strings out(Rf_xlength(vec));
+      R_xlen_t len = Rf_xlength(vec);
+
+      for (R_xlen_t i = 0; i < len; i++) {
+        SEXP str_elt = reinterpret_cast<SEXP>(STRING_ELT(vec, i));
+        out[i] = str_elt;
+      }
+
+      return out;
```
Comment (jonkeane) [inline r/src/arrow_types.h:203]: I believe this chunk is necessary to return the array of strings here. But oddly(??) when I tried this block as simply `return STRING_ELT(vec, 0);` (which would return just the first element IIUC), all tests passed. So maybe I misunderstand what's happening in the MutableBuffer there and we actually only need an object of the right type? Or we don't have test coverage that ensures that the full vector is there?

**Comment by nealrichardson** [comment]
I don't understand this code well enough to have much to say. I did look at the part of WRE that the CRAN check points to, and it suggests using `DATAPTR_RO` instead of `DATAPTR`: https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#Moving-into-C-API-compliance

Is that not an option for us?

**Comment by jonkeane** [comment]
> suggests using DATAPTR_RO instead of DATAPTR: https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#Moving-into-C-API-compliance
> 
> Is that not an option for us?

It is an option in one place and I did use it there, but not all: I would get segfaults/illegal access in the places that I didn't use it. If I'm reading the code correctly, those are places where we are actually mutating in place

File: r/src/arrow_types.h (hunk 2 above)
Comment (amoeba) [reply r/src/arrow_types.h:203]: Just doing `return STRING_ELT(vec, 0)` actually makes sense to me since it looks like we just need a pointer to the same address as what we'd get with DATAPTR. Seems like that's what `STRING_ELT(vec, 0)` should accomplish. It does seem like a strange way to do it but it also seems like what we're doing here is already breaking the rules CRAN wants us to play by. If it works, I'm +1.

File: r/src/altrep.cpp (hunk 1 above)
Comment (amoeba) [reply r/src/altrep.cpp:1314]: `DATAPTR` and `STRING_ELT` work a bit different for altrep so it seems reasonable to me to assume we were implicitly materializing before and no longer are with `STRING_ELT`. It seems like this is an assumption of the test that no longer holds and the expectation could be removed.

**Review by amoeba — COMMENTED** [review]
Thanks for working on this. I took a look through and left a couple of comments. Once the altrep test failures get figured out I'll be a +1 on this.

File: r/src/arrow_types.h (hunk 2 above)
Comment (jonkeane) [reply r/src/arrow_types.h:203]: Ok, I've also commented this to be explicit for the next person

File: r/tests/testthat/test-altrep.R [hunk 3]
```diff
@@ -170,7 +170,7 @@ test_that("element access methods for int32 ALTREP with nulls", {
   expect_identical(test_arrow_altrep_copy_by_region(altrep, 123), original)
   expect_false(test_arrow_altrep_is_materialized(altrep))
 
-  # because there are no nulls, DATAPTR() does not materialize
+  # because there are nulls, DATAPTR() does materialize
```
Comment (jonkeane) [inline r/tests/testthat/test-altrep.R:173]: This comment change and the one below are not _behavior_ changes with this PR, but I think the comments were simply wrong (either old or copy pasted). I've tried to correct them to be accurate descriptions of what's going on (but see "does not materialize" and then two lines later `expect_true(test_arrow_altrep_is_materialized(altrep))` is at odds with each other

**Comment by jonkeane** [comment]
@github-actions crossbow submit -g r

File: r/src/altrep.cpp [hunk 4]
```diff
@@ -220,7 +220,11 @@ struct AltrepVectorPrimitive : public AltrepVectorBase<AltrepVectorPrimitive<sex
       SEXP copy = PROTECT(Rf_allocVector(sexp_type, size));
 
       // copy the data from the array, through Get_region
-      Get_region(alt, 0, size, reinterpret_cast<c_type*>(DATAPTR(copy)));
+      if constexpr (std::is_same_v<c_type, double>) {
+        Get_region(alt, 0, size, reinterpret_cast<double*>(REAL(copy)));
```
Comment (paleolimbot) [inline r/src/altrep.cpp:224]:
```suggestion
        Get_region(alt, 0, size, REAL(copy));
```

(I think this should work)

File: r/src/altrep.cpp [hunk 5]
```diff
@@ -892,7 +904,19 @@ struct AltrepVectorString : public AltrepVectorBase<AltrepVectorString<Type>> {
...
+    // string and place the SEXPs in it ourselves with STRING_ELT()
+    SEXP materialized = Materialize(alt);
+
+    R_xlen_t len = XLENGTH(materialized);
+    void** str_array = (void**)R_alloc(len, sizeof(void*));
+    for (R_xlen_t i = 0; i < len; i++) {
+      str_array[i] = (void*)STRING_ELT(materialized, i);
+    }
+
+    return str_array;
```
Comment (paleolimbot) [inline r/src/altrep.cpp:918]:
```suggestion
    return const_cast<void*>(DATAPTR_RO(Materialize(alt)));
```

(Not sure if this works but it's worth a shot!)

File: r/src/arrow_types.h [hunk 6]
```diff
@@ -173,14 +173,33 @@ template <typename RVector>
...
+    if (TYPEOF(vec) == LGLSXP) {
+      return LOGICAL(vec);
+    } else if (TYPEOF(vec) == INTSXP) {
+      return INTEGER(vec);
+    } else if (TYPEOF(vec) == REALSXP) {
+      return REAL(vec);
+    } else if (TYPEOF(vec) == CPLXSXP) {
+      return COMPLEX(vec);
+    } else if (TYPEOF(vec) == STRSXP) {
+      // Technically this returns the address to the first element of the string vector
```
Comment (paleolimbot) [inline r/src/arrow_types.h:195]: This should almost certainly error if I'm reading this properly (I don't think we should ever be exposing the internal `SEXP**` to Arrow and I don't think we ever do?)

File: r/src/altrep.cpp [hunk 7]
```diff
@@ -1267,23 +1293,23 @@ sexp test_arrow_altrep_copy_by_dataptr(sexp x) {
...
       out[i] = ptr[i];
     }
     return out;
   } else if (TYPEOF(x) == STRSXP) {
     cpp11::writable::strings out(Rf_xlength(x));
-    SEXP* ptr = reinterpret_cast<SEXP*>(DATAPTR(x));
     for (R_xlen_t i = 0; i < n; i++) {
-      out[i] = ptr[i];
+      SEXP str_elt = reinterpret_cast<SEXP>(STRING_ELT(x, i));
+      out[i] = str_elt;
```
Comment (paleolimbot) [inline r/src/altrep.cpp:1312]: I think you can remove this branch since it quite literally peeks into the internals they're trying to make opaque and it's just test code. A more real-world application would be to find where r-source does this and make sure that method works on our ALTREP. I think, but don't know, that `SET_STRING_ELT()` and `match()` will call DATAPTR().

File: r/src/altrep.cpp (hunk 4 above)
Comment (jonkeane) [reply r/src/altrep.cpp:224]: Ah, yes! Thanks (and same for the following branch too, which I got)

File: r/src/altrep.cpp (hunk 5 above)
Comment (jonkeane) [reply r/src/altrep.cpp:920]: Yup! that works. Thanks 🙏

File: r/src/arrow_types.h (hunk 6 above)
Comment (jonkeane) [reply r/src/arrow_types.h:195]: _nods_ yeah, I agree this is weird! Did you see this comment (and especially the code block that was there, I've added below in case github folding hides it) https://github.com/apache/arrow/pull/45951#discussion_r2019797949 would this code be better here?

```
    } else if (TYPEOF(vec) == STRSXP) {
      cpp11::writable::strings out(Rf_xlength(vec));
      R_xlen_t len = Rf_xlength(vec);

      for (R_xlen_t i = 0; i < len; i++) {
        SEXP str_elt = reinterpret_cast<SEXP>(STRING_ELT(vec, i));
        out[i] = str_elt;
      }

      return out;
    }
```

File: r/src/altrep.cpp [hunk 8]
```diff
@@ -1267,23 +1285,23 @@ sexp test_arrow_altrep_copy_by_dataptr(sexp x) {
 
   if (TYPEOF(x) == INTSXP) {
     cpp11::writable::integers out(Rf_xlength(x));
-    int* ptr = reinterpret_cast<int*>(DATAPTR(x));
+    int* ptr = reinterpret_cast<int*>(INTEGER(x));
```
Comment (paleolimbot) [inline r/src/altrep.cpp:1288]:
```suggestion
    int* ptr = INTEGER(x);
```

(and below as well)

File: r/src/altrep.cpp (hunk 7 above)
Comment (paleolimbot) [reply r/src/altrep.cpp:1304]: Yes, you'd have to remove the test that depends on it, too. This test was added in a follow up to https://github.com/apache/arrow/pull/13415 which fixed a case of multiple materializations when R's internals called DATAPTR(). As written, this test no longer calls DATAPTR() for a character vector, so it may be less confusing to remove it.

In R  some things that might call DATAPTR are `altrep_vctr[1] = "something else"`, `unique()`, and `match(altrep_vctr, c("one", "two", "three"))` (one could check with the debugger or a print to see if it's actually getting called).

File: r/src/arrow_types.h (hunk 6 above)
Comment (paleolimbot) [reply r/src/arrow_types.h:195]: I think erroring is a better option here (I believe exposing the bytes of a STRSXP's data buffer would be a programming error on our end).

File: r/tests/testthat/test-altrep.R [hunk 9]
```diff
@@ -244,11 +244,12 @@ test_that("element access methods for character ALTREP", {
   expect_identical(test_arrow_altrep_copy_by_element(altrep), original)
   expect_false(test_arrow_altrep_is_materialized(altrep))
 
-  # DATAPTR() should always materialize for strings
+  # DATAPTR() does not materialize
```
[the remark this answers is not in the document]
Comment (paleolimbot) [reply r/tests/testthat/test-altrep.R:247]: Yes, this was the crux of https://github.com/apache/arrow/pull/13415 (we were materializing the entire array multiple times when R's internals called DATAPTR()).

File: r/src/altrep.cpp [hunk 10]
```diff
@@ -220,7 +220,11 @@ struct AltrepVectorPrimitive : public AltrepVectorBase<AltrepVectorPrimitive<sex
       SEXP copy = PROTECT(Rf_allocVector(sexp_type, size));
 
       // copy the data from the array, through Get_region
-      Get_region(alt, 0, size, reinterpret_cast<c_type*>(DATAPTR(copy)));
+      if constexpr (std::is_same_v<c_type, double>) {
+        Get_region(alt, 0, size, REAL(copy));
+      } else {
```
Comment (paleolimbot) [inline r/src/altrep.cpp:225]: Here and one other place would benefit from the `if constexpr (std::is_same_v<c_type, int>)` suggestion as well

File: r/src/altrep.cpp (hunk 7 above)
Comment (jonkeane) [reply r/src/altrep.cpp:1304]: Ah, got it. Yeah if it's not helping us I agree removing it is the way to go. I tried the reprexes with `unique()` on my branch here as well as on released arrow and the results are comparable so I think we're ok. 

I'm curious though — were there other tests we had that would have caught the multiple materialization issue? Or were these the ones that did that?

Released arrow:
```
> library(arrow)
> df1 <- tibble::tibble(x=as.character(floor(runif(1000000) * 20)))
> write_parquet(df1,"./test.parquet")
> df2 <- read_parquet("./test.parquet")
> system.time(unique(df1$x))
   user  system elapsed 
  0.014   0.000   0.015 
> system.time(unique(df2$x))
   user  system elapsed 
  0.113   0.001   0.114 
```

This branch:
```
> library(arrow)
> df1 <- tibble::tibble(x=as.character(floor(runif(1000000) * 20)))
> write_parquet(df1,"./test.parquet")
df2 <- read_parquet("./test.parquet")
system.time(unique(df1$x))
system.time(unique(df2$x))
> df2 <- read_parquet("./test.parquet")
> system.time(unique(df1$x))
   user  system elapsed 
  0.014   0.001   0.014 
> system.time(unique(df2$x))
   user  system elapsed 
  0.106   0.001   0.107 
```

File: r/src/altrep.cpp (hunk 8 above)
Comment (jonkeane) [reply r/src/altrep.cpp:1288]: Thanks!

File: r/tests/testthat/test-altrep.R (hunk 9 above)
[the remark this answers is not in the document]
Comment (jonkeane) [reply r/tests/testthat/test-altrep.R:247]: Ah ok, I'm updating these to use `match()` to confirm that internally calling `DATAPTR()` (since we can't do that ourselves directly anymore) does materialize the vector.

**Comment by jonkeane** [comment]
@github-actions crossbow submit -g r

**Comment by jonkeane** [comment]
Failres: `test-r-rstudio-r-base-4.1-opensuse155` and `test-r-offline-maximal` are unrelated / being fixed elsewhere.

**Review by amoeba — APPROVED** [review]
+1

File: r/src/altrep.cpp [hunk 11]
```diff
@@ -531,7 +552,7 @@ struct AltrepFactor : public AltrepVectorBase<AltrepFactor> {
       SEXP copy = PROTECT(Rf_allocVector(INTSXP, size));
 
       // copy the data from the array, through Get_region
-      Get_region(alt, 0, size, reinterpret_cast<int*>(DATAPTR(copy)));
+      Get_region(alt, 0, size, reinterpret_cast<int*>(INTEGER(copy)));
```
Comment (paleolimbot) [inline r/src/altrep.cpp:555]:
```suggestion
      Get_region(alt, 0, size, INTEGER(copy));
```

File: r/src/altrep.cpp (hunk 7 above)
Comment (paleolimbot) [reply r/src/altrep.cpp]: Thanks for checking that! I don't recall any tests that checked the whether something was materialized more than once but it was quite a long time ago 🙂

File: r/tests/testthat/test-altrep.R (hunk 9 above)
[the remark this answers is not in the document]
Comment (paleolimbot) [reply r/tests/testthat/test-altrep.R]: Thanks!

**Review by paleolimbot — APPROVED** [review]
Thanks!

File: r/src/altrep.cpp (hunk 11 above)
Comment (jonkeane) [reply r/src/altrep.cpp:555]: Ah yes, thanks for that reminder, I found a few others too

**Comment by jonkeane** [comment]
@assignUser would it be possible to pull this into 20? We will need to patch it in our CRAN release regardless, but it would be nice to have it on the actual release.

**Comment by assignUser** [comment]
Of course!

**Comment by h-vetinari** [comment]
I believe this PR is the likely reason for the following failure I'm seeing in https://github.com/conda-forge/r-arrow-feedstock/pull/101:

```
In file included from r_to_arrow.cpp:18:
.\./arrow_types.h:193:14: error: called object type 'arrow::r::RVectorType' is not a function or function pointer
  193 |       return COMPLEX(vec);
      |              ^~~~~~~
.\./arrow_types.h:176:50: note: in instantiation of member function 'arrow::r::RBuffer<cpp11::r_vector<int>>::getDataPointer' requested here
  176 |       : MutableBuffer(reinterpret_cast<uint8_t*>(getDataPointer(vec)),
      |                                                  ^
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.43.34808\include\xutility:506:58: note: in instantiation of member function 'arrow::r::RBuffer<cpp11::r_vector<int>>::RBuffer' requested here
  506 |         ::new (static_cast<void*>(_STD addressof(_Obj))) _Ty(_STD forward<_Types>(_Args)...);
      |                                                          ^
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.43.34808\include\memory:2092:18: note: in instantiation of function template specialization 'std::_Construct_in_place<arrow::r::RBuffer<cpp11::r_vector<int>>, cpp11::r_vector<int> &>' requested here
 2092 |             _STD _Construct_in_place(_Storage._Value, _STD forward<_Types>(_Args)...);
      |                  ^
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.43.34808\include\memory:2903:26: note: in instantiation of function template specialization 'std::_Ref_count_obj2<arrow::r::RBuffer<cpp11::r_vector<int>>>::_Ref_count_obj2<cpp11::r_vector<int> &>' requested here
 2903 |     const auto _Rx = new _Ref_count_obj2<_Ty>(_STD forward<_Types>(_Args)...);
      |                          ^
r_to_arrow.cpp:1240:53: note: in instantiation of function template specialization 'std::make_shared<arrow::r::RBuffer<cpp11::r_vector<int>>, cpp11::r_vector<int> &>' requested here
 1240 |                                                std::make_shared<RBuffer<RVector>>(vec)};
      |                                                     ^
r_to_arrow.cpp:1283:12: note: in instantiation of function template specialization 'arrow::r::MakeSimpleArray<13, cpp11::r_vector<int>, arrow::Int32Type>' requested here
 1283 |     return MakeSimpleArray<INTSXP, cpp11::integers, Int32Type>(x);
      |            ^
```

This smells like macro leakage from the UCRT headers (e.g. if there's something called `COMPLEX` there already), which is always an issue on windows... C.f. `NOMINMAX`, `WIN32_LEAN_AND_MEAN` etc.

We're using a clang on windows (adapted for the needs of R packages), together with the standard windows runtimes. CC @xhochy
