### PR TITLE
GH-34044: [Go] Fix build with noasm tag

### LINKED ISSUE #34044: [Go] Build fails with noasm build tag
### Describe the bug, including details regarding any error messages, version, and platform.

A Go build with the noasm build tag fails.
```console
$ git describe --dirty --tags
apache-arrow-12.0.0.dev-41-gecb1f2e31

$ go build -tags noasm ./...
# github.com/apache/arrow/go/v12/arrow/compute/internal/kernels
arrow/compute/internal/kernels/basic_arithmetic_noasm.go:27:9: undefined: getGoArithmeticOpFloatingSameType
arrow/compute/internal/kernels/basic_arithmetic_noasm.go:35:9: undefined: getGoArithmeticFixedIntOut
```

### Component(s)

Go

### PR DESCRIPTION
**Pull request by nwt**
Fix the following build failure.

    $ go build -tags noasm ./...
    # github.com/apache/arrow/go/v12/arrow/compute/internal/kernels
    arrow/compute/internal/kernels/basic_arithmetic_noasm.go:27:9: undefined: getGoArithmeticOpFloatingSameType
    arrow/compute/internal/kernels/basic_arithmetic_noasm.go:35:9: undefined: getGoArithmeticFixedIntOut

Closes #34044.

### CODE REVIEW

**Review by zeroshade — APPROVED** [review]
The build failures aren't related to this change (and get fixed in #34039) so this looks good.

Thanks much!
