### PR TITLE
ARROW-16477: [Packaging][RPM] Add support for Amazon Linux 2 on aarch64

### PR DESCRIPTION
**Pull request by kou**
CentOS 7 on aarch64 isn't supported because we need GCC 7 or later for the platform.
verify-release-candidate.sh doesn't verify CentOS 7 packages on aarch64.

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit almalinux-* amazon-linux-* centos-*

**Comment by kou** [comment]
@github-actions crossbow submit almalinux-* amazon-linux-* centos-*

**Comment by kou** [comment]
@github-actions crossbow submit amazon-linux-2-arm64 centos-7-arm64

**Comment by cyb70289** [comment]
Can I test the two jobs on my local arm64 machine?

**Comment by kou** [comment]
Yes. Here are command lines of them:

```console
$ cd dev/tasks/linux-packages/apache-arrow
$ gem install apt-dists-merge
$ rake yum:build BUILD_DIR=build YUM_TARGETS=amazon-linux-2-aarch64
$ rake yum:build BUILD_DIR=build YUM_TARGETS=centos-7-aarch64
```

Note that you need to install Ruby. You can install Ruby by `apt install ruby rake` on Debian/Ubuntu.

I'm also running these jobs on local amd64 machine with QEMU.

**Comment by cyb70289** [comment]
Looks xsimd failed to build with gcc4.8.5. Is it necessary to make it work with gcc4.8?

```
../src/arrow/util/utf8.h:244:22: error: expected type-specifier
   using simd_batch = xsimd::make_sized_batch_t<int8_t, 16>;
                      ^
```

**Comment by cyb70289** [comment]
> Hmm, is it OK that we disable SIMD for CentOS 7 and aarch64?

I think it's OK.

**Comment by kou** [comment]
OK. I'll disable SIMD on CentOS 7 aarch64.

**Comment by kou** [comment]
@github-actions crossbow submit amazon-linux-2-arm64 centos-7-arm64

**Comment by kou** [comment]
https://app.travis-ci.com/github/ursacomputing/crossbow/builds/252684277#L4242

```text
/root/rpmbuild/BUILD/apache-arrow-9.0.0.dev305/cpp/src/arrow/compute/kernels/codegen_internal.h:314:25: internal compiler error: in expand_shift_1, at expmed.c:2245
```

[Bug 72738](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=72738) - internal compiler error: in expand_shift_1, at expmed.c:2318

> Fixed for GCC 7 by [r7-3897](https://gcc.gnu.org/cgi-bin/gcc-gitref.cgi?r=r7-3897).

We need to use GCC 7 or later to support CentOS 7 aarch64. So I give up to enable CentOS 7 aarch64.

**Review by cyb70289 — APPROVED** [review]

**Comment by kou** [comment]
+1
