### PR TITLE
GH-51140: [C++] Require simdjson 4.3.0 for fractured_json APIs

### LINKED ISSUE #51140: [C++] Require simdjson 4.3.0 for fractured_json APIs
### Describe the bug, including details regarding any error messages, version, and platform.

Commit c8240bd63a introduced use of `simdjson::fractured_json_options` and `simdjson::fractured_json_string` (commit 06e3b9a864 later moved that).

These APIs are available starting with [simdjson 4.3.0](https://github.com/simdjson/simdjson/releases/tag/v4.3.0),
but `ARROW_SIMDJSON_REQUIRED_VERSION` is still set to `4.0.0`
https://github.com/apache/arrow/blob/a62870ce4c7a7c9b570fbb5d1376cb482f144659/cpp/cmake_modules/ThirdpartyToolchain.cmake#L2855

CMake may accept system simdjson 4.2.3 install and fail:

```console
[2/800] Building CXX object src/arrow/CMake.../arrow_util.dir/util/simdjson_internal.cc.
FAILED: [code=1] src/arrow/CMakeFiles/arrow_util.dir/util/simdjson_internal.cc.o ... 

In file included from ...cpp/src/arrow/util/simdjson_internal.cc:18:
...cpp/src/arrow/util/simdjson_internal.h:94:23: error: no type named 'fractured_json_options' in namespace 'simdjson'
   94 |       const simdjson::fractured_json_options& options = {}) const;
      |             ~~~~~~~~~~^
...cpp/src/arrow/util/simdjson_internal.cc:353:21: error: no type named 'fractured_json_options' in namespace 'simdjson'
  353 |     const simdjson::fractured_json_options& options) const {
      |           ~~~~~~~~~~^
...cpp/src/arrow/util/simdjson_internal.cc:355:20: error: no member named 'fractured_json_string' in namespace 'simdjson'
  355 |   return simdjson::fractured_json_string(json, options);
      |          ~~~~~~~~~~^
3 errors generated.
[3/800] Building CXX object src/arrow/CMake...ation.dir/integration/json_integration.cc.
FAILED: [code=1] src/arrow/CMakeFiles/arrow_integration.dir/integration/json_integration.cc.o 
...
```

This was reproduced on macOS with system simdjson 4.2.3.
Builds using bundled simdjson 4.6.4 or Conda simdjson 4.6.4 are not affected 
https://github.com/apache/arrow/blob/a4e3909bcf59911316a696990f1eb1d583cddae1/cpp/thirdparty/versions.txt#L105

### Component(s)

C++

### PR DESCRIPTION
**Pull request by tadeja**
### Rationale for this change
Fix #51140, CMake configuration should not accept simdjson earlier than v4.3.0.

### What changes are included in this PR?
Set ARROW_SIMDJSON_REQUIRED_VERSION to "4.3.0"

### Are these changes tested?
Yes. Locally, CMake configuration rejects system simdjson 4.2.3 now
`CMake Error at cmake_modules/ThirdpartyToolchain.cmake:316 (message):`
`  Couldn't find simdjson >= 4.3.0`

### Are there any user-facing changes?
No.

* GitHub Issue: #51140

### CODE REVIEW

**Comment by tadeja** [comment]
@github-actions crossbow submit test-build-vcpkg-win test-ubuntu-22.04-cpp-bundled

**Review by kou — APPROVED** [review]
+1

**Comment by rok** [comment]
Regarding simdjson version - we had a version discussion here already - https://github.com/apache/arrow/pull/50568#discussion_r3626750364. TLDR: [ubuntu](https://repology.org/project/simdjson/versions) lags, only 26.0.10 has 4.6.8, while 26.0.4 has 4.2.4.

**Comment by Reranko05** [comment]
> Regarding simdjson version - we had a version discussion here already - [#50568 (comment)](https://github.com/apache/arrow/pull/50568#discussion_r3626750364). TLDR: [ubuntu](https://repology.org/project/simdjson/versions) lags, only 26.0.10 has 4.6.8, while 26.0.4 has 4.2.4.

@pitrou Should we use `fractured_json_string`  like suggested in https://github.com/apache/arrow/pull/51014#discussion_r3871693689, or should I avoid it for compatibility with older simdjson versions?

**Comment by pitrou** [comment]
> Regarding simdjson version - we had a version discussion here already - [#50568 (comment)](https://github.com/apache/arrow/pull/50568#discussion_r3626750364). TLDR: [ubuntu](https://repology.org/project/simdjson/versions) lags, only 26.0.10 has 4.6.8, while 26.0.4 has 4.2.4.

Do you suggest we support simdjson 1.0.2 to be compatible with Ubuntu 22.04?

**Comment by Reranko05** [comment]
> Do you suggest we support simdjson 1.0.2 to be compatible with Ubuntu 22.04?

I think that's okay, never mind. We can't go that far back anyway :)

**Comment by rok** [comment]
(In case you're asking me too) @pitrou I don't have a strong opinion. As per @kou we can bundle: https://github.com/apache/arrow/pull/50568#discussion_r3626750364
