### PR TITLE
GH-36405: [C++][ORC] Upgrade ORC to 1.9.0

### LINKED ISSUE #36405: [C++][ORC] Failed to build ORC adapter test with ORC 1.9.0
### Describe the enhancement requested

https://ci.appveyor.com/project/ApacheSoftwareFoundation/arrow/builds/47432784

```text
[258/420] Building CXX object src\arrow\adapters\orc\CMakeFiles\arrow-orc-adapter-test.dir\adapter_test.cc.obj
FAILED: src/arrow/adapters/orc/CMakeFiles/arrow-orc-adapter-test.dir/adapter_test.cc.obj 
C:\Miniconda38-x64\envs\arrow\Library\bin\ccache.exe C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\cl.exe  /nologo /TP -DABSL_CONSUME_DLL -DARROW_HAVE_RUNTIME_AVX2 -DARROW_HAVE_RUNTIME_AVX512 -DARROW_HAVE_RUNTIME_BMI2 -DARROW_HAVE_RUNTIME_SSE4_2 -DARROW_HAVE_SSE4_2 -DARROW_HDFS -DARROW_MIMALLOC -DARROW_S3_HAS_CRT -DARROW_WITH_BROTLI -DARROW_WITH_BZ2 -DARROW_WITH_LZ4 -DARROW_WITH_RE2 -DARROW_WITH_SNAPPY -DARROW_WITH_UTF8PROC -DARROW_WITH_ZLIB -DARROW_WITH_ZSTD -DAWS_AUTH_USE_IMPORT_EXPORT -DAWS_CAL_USE_IMPORT_EXPORT -DAWS_CHECKSUMS_USE_IMPORT_EXPORT -DAWS_COMMON_USE_IMPORT_EXPORT -DAWS_COMPRESSION_USE_IMPORT_EXPORT -DAWS_CRT_CPP_USE_IMPORT_EXPORT -DAWS_EVENT_STREAM_USE_IMPORT_EXPORT -DAWS_HTTP_USE_IMPORT_EXPORT -DAWS_IO_USE_IMPORT_EXPORT -DAWS_MQTT_USE_IMPORT_EXPORT -DAWS_MQTT_WITH_WEBSOCKETS -DAWS_S3_USE_IMPORT_EXPORT -DAWS_SDKUTILS_USE_IMPORT_EXPORT -DAWS_SDK_VERSION_MAJOR=1 -DAWS_SDK_VERSION_MINOR=10 -DAWS_SDK_VERSION_PATCH=13 -DAWS_USE_IO_COMPLETION_PORTS -DBOOST_ALL_DYN_LINK -DBOOST_ALL_NO_LIB -DGTEST_LINKED_AS_SHARED_LIBRARY=1 -DPROTOBUF_USE_DLLS -DURI_STATIC_BUILD -DUSE_IMPORT_EXPORT -DUSE_IMPORT_EXPORT=1 -DUSE_WINDOWS_DLL_SEMANTICS -D_CRT_SECURE_NO_WARNINGS -D_ENABLE_EXTENDED_ALIGNED_STORAGE -IC:\projects\arrow\cpp\build\src -IC:\projects\arrow\cpp\src -IC:\projects\arrow\cpp\src\generated -external:IC:\Miniconda38-x64\envs\arrow\Library\include -external:IC:\projects\arrow\cpp\thirdparty\flatbuffers\include -external:IC:\projects\arrow\cpp\thirdparty\hadoop\include -external:IC:\OpenSSL-v30-Win64-temp\include -external:IC:\projects\arrow\cpp\build\mimalloc_ep\src\mimalloc_ep\include\mimalloc-2.0 -external:W0 /DWIN32 /D_WINDOWS /GR /EHsc /D_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING  /EHsc /wd5105 /bigobj /utf-8 /W3 /wd4800 /wd4996 /wd4065  /WX /MP /MD /Od /UNDEBUG -std:c++17 -MD /showIncludes /Fosrc\arrow\adapters\orc\CMakeFiles\arrow-orc-adapter-test.dir\adapter_test.cc.obj /Fdsrc\arrow\adapters\orc\CMakeFiles\arrow-orc-adapter-test.dir\ /FS -c C:\projects\arrow\cpp\src\arrow\adapters\orc\adapter_test.cc
C:\projects\arrow\cpp\src\arrow\adapters\orc\adapter_test.cc(1044): error C2668: 'orc::Type::createRowBatch': ambiguous call to overloaded function
C:\Miniconda38-x64\envs\arrow\Library\include\orc/Type.hh(81): note: could be 'std::unique_ptr<orc::ColumnVectorBatch,std::default_delete<orc::ColumnVectorBatch>> orc::Type::createRowBatch(uint64_t,orc::MemoryPool &,bool,bool) const'
C:\Miniconda38-x64\envs\arrow\Library\include\orc/Type.hh(78): note: or       'std::unique_ptr<orc::ColumnVectorBatch,std::default_delete<orc::ColumnVectorBatch>> orc::Type::createRowBatch(uint64_t,orc::MemoryPool &,bool) const'
C:\projects\arrow\cpp\src\arrow\adapters\orc\adapter_test.cc(1044): note: while trying to match the argument list '(int64_t, orc::MemoryPool)'
C:\projects\arrow\cpp\src\arrow\adapters\orc\adapter_test.cc(1050): error C3536: 'orc_batch': cannot be used before it is initialized
C:\projects\arrow\cpp\src\arrow\adapters\orc\adapter_test.cc(1049): error C2660: 'arrow::adapters::orc::WriteBatch': function does not take 4 arguments
C:\projects\arrow\cpp\src\arrow/adapters/orc/util.h(59): note: see declaration of 'arrow::adapters::orc::WriteBatch'
C:\projects\arrow\cpp\src\arrow\adapters\orc\adapter_test.cc(1054): error C2660: 'arrow::adapters::orc::AppendBatch': function does not take 4 arguments
C:\projects\arrow\cpp\src\arrow/adapters/orc/util.h(46): note: see declaration of 'arrow::adapters::orc::AppendBatch'
[259/420] Building CXX object src\parquet\CMakeFiles\parquet_shared.dir\Unity\unity_5_cxx.cxx.obj
ninja: build stopped: subcommand failed.
```

### Component(s)

C++

### PR DESCRIPTION
**Pull request by wgtmac**
### Rationale for this change

Apache ORC has released 1.9.0 recently: https://orc.apache.org/news/2023/06/28/ORC-1.9.0/

The code base does not compile if we upgrade directly due to a new API below:
```cpp
    virtual std::unique_ptr<ColumnVectorBatch> createRowBatch(
        uint64_t size, MemoryPool& pool,
        bool encoded = false) const = 0;

    virtual std::unique_ptr<ColumnVectorBatch> createRowBatch(
        uint64_t size, MemoryPool& pool, bool encoded = false,
        bool useTightNumericVector = false) const = 0;

```

### What changes are included in this PR?

Explicitly specify which overload of `createRowBatch` to use in the orc test.

### Are these changes tested?

Yes, make sure all tests build and pass.

### Are there any user-facing changes?

NO.
* Closes: #36405

### CODE REVIEW

**Comment by wgtmac** [comment]
@kou Please take a look, thanks!

**Comment by kou** [comment]
Thanks!

Can we write a code that works with both of ORC 1.9.0 and 1.8.4?

Our CI job that still uses ORC 1.8.4 failed with this change:

https://github.com/apache/arrow/actions/runs/5419179225/jobs/9852016855?pr=36406#step:6:2464

```text
FAILED: src/arrow/adapters/orc/CMakeFiles/arrow-orc-adapter-test.dir/adapter_test.cc.o 
/opt/conda/envs/arrow/bin/ccache /opt/conda/envs/arrow/bin/x86_64-conda-linux-gnu-c++ -DARROW_EXTRA_ERROR_CONTEXT -DARROW_HAVE_RUNTIME_AVX2 -DARROW_HAVE_RUNTIME_AVX512 -DARROW_HAVE_RUNTIME_BMI2 -DARROW_HAVE_RUNTIME_SSE4_2 -DARROW_HAVE_SSE4_2 -DARROW_HDFS -DARROW_MIMALLOC -DARROW_S3_HAS_CRT -DARROW_WITH_BENCHMARKS_REFERENCE -DARROW_WITH_BROTLI -DARROW_WITH_BZ2 -DARROW_WITH_LZ4 -DARROW_WITH_RE2 -DARROW_WITH_SNAPPY -DARROW_WITH_UTF8PROC -DARROW_WITH_ZLIB -DARROW_WITH_ZSTD -DAWS_AUTH_USE_IMPORT_EXPORT -DAWS_CAL_USE_IMPORT_EXPORT -DAWS_CHECKSUMS_USE_IMPORT_EXPORT -DAWS_COMMON_USE_IMPORT_EXPORT -DAWS_COMPRESSION_USE_IMPORT_EXPORT -DAWS_CRT_CPP_USE_IMPORT_EXPORT -DAWS_EVENT_STREAM_USE_IMPORT_EXPORT -DAWS_HTTP_USE_IMPORT_EXPORT -DAWS_IO_USE_IMPORT_EXPORT -DAWS_MQTT_USE_IMPORT_EXPORT -DAWS_MQTT_WITH_WEBSOCKETS -DAWS_S3_USE_IMPORT_EXPORT -DAWS_SDKUTILS_USE_IMPORT_EXPORT -DAWS_SDK_VERSION_MAJOR=1 -DAWS_SDK_VERSION_MINOR=10 -DAWS_SDK_VERSION_PATCH=13 -DAWS_USE_EPOLL -DGTEST_LINKED_AS_SHARED_LIBRARY=1 -DURI_STATIC_BUILD -I/build/cpp/src -I/arrow/cpp/src -I/arrow/cpp/src/generated -isystem /arrow/cpp/thirdparty/flatbuffers/include -isystem /arrow/cpp/thirdparty/hadoop/include -isystem /build/cpp/jemalloc_ep-prefix/src -isystem /build/cpp/mimalloc_ep/src/mimalloc_ep/include/mimalloc-2.0 -isystem /build/cpp/googletest_ep-prefix/include -Wno-noexcept-type -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /opt/conda/envs/arrow/include -fdiagnostics-color=always -fuse-ld=gold  -Wall -Wno-conversion -Wno-sign-conversion -Wunused-result -Wdate-time -fno-semantic-interposition -msse4.2  -g -Werror -O0 -ggdb -g1 -std=c++17 -fPIE -pthread -DS2N_KYBER512R3_AVX2_BMI2 -DS2N_STACKTRACE -DS2N_CPUID_AVAILABLE -DS2N_FEATURES_AVAILABLE -fPIC -DS2N_FALL_THROUGH_SUPPORTED -DS2N___RESTRICT__SUPPORTED -DS2N_MADVISE_SUPPORTED -DS2N_CLONE_SUPPORTED -DS2N_LIBCRYPTO_SUPPORTS_EVP_MD5_SHA1_HASH -DS2N_LIBCRYPTO_SUPPORTS_EVP_RC4 -DS2N_LIBCRYPTO_SUPPORTS_EVP_MD_CTX_SET_PKEY_CTX -MD -MT src/arrow/adapters/orc/CMakeFiles/arrow-orc-adapter-test.dir/adapter_test.cc.o -MF src/arrow/adapters/orc/CMakeFiles/arrow-orc-adapter-test.dir/adapter_test.cc.o.d -o src/arrow/adapters/orc/CMakeFiles/arrow-orc-adapter-test.dir/adapter_test.cc.o -c /arrow/cpp/src/arrow/adapters/orc/adapter_test.cc
/arrow/cpp/src/arrow/adapters/orc/adapter_test.cc: In function 'void arrow::{anonymous}::TestUnionConversion(std::shared_ptr<arrow::Array>)':
/arrow/cpp/src/arrow/adapters/orc/adapter_test.cc:1046:31: error: no matching function for call to 'orc::Type::createRowBatch(int64_t, orc::MemoryPool&, bool, bool)'
 1046 |       orc_type->createRowBatch(array->length(), *liborc::getDefaultPool(),
      |       ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1047 |                                /*encoded=*/false, /*useTightNumericVector=*/false);
      |                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /opt/conda/envs/arrow/include/orc/Common.hh:23,
                 from /opt/conda/envs/arrow/include/orc/Reader.hh:23,
                 from /opt/conda/envs/arrow/include/orc/OrcFile.hh:25,
                 from /arrow/cpp/src/arrow/adapters/orc/adapter_test.cc:21:
/opt/conda/envs/arrow/include/orc/Type.hh:73:47: note: candidate: 'virtual std::unique_ptr<orc::ColumnVectorBatch> orc::Type::createRowBatch(uint64_t, orc::MemoryPool&, bool) const'
   73 |     virtual ORC_UNIQUE_PTR<ColumnVectorBatch> createRowBatch(uint64_t size,
      |                                               ^~~~~~~~~~~~~~
/opt/conda/envs/arrow/include/orc/Type.hh:73:47: note:   candidate expects 3 arguments, 4 provided
```

**Comment by wgtmac** [comment]
Unfortunately there isn't any approach to work for both 1.9.0 and 1.8.4 except disabling this test temporarily.

**Comment by kou** [comment]
Oh... I found the `ORC_VERSION` macro but we can't use it for this case because it's a string...

We can detect ORC version by CMake and export it to C++ but it'll be overkill for this.

Could you disable the test for now?

**Comment by wgtmac** [comment]
I just workaround this by creating a writer to create the batch instead of directly calling on the type object. I think this is fine as it is only used in the test. @kou

**Review by kou — APPROVED** [review]
+1

The R failures are #36396.

**Comment by dongjoon-hyun** [comment]
Thank you so much, @wgtmac and @kou .
