### ISSUE TITLE
[C++][R] #include <ranges> in vector_select_k.cc breaks macOS CRAN and wasm builds

### ISSUE THREAD

**Issue by thisisnic** [apache/arrow#50295]
`vector_select_k.cc:20` includes `<ranges>`, which is not available on the macOS CRAN toolchain or emscripten:

https://github.com/apache/arrow/blob/d0919579cb/cpp/src/arrow/compute/kernels/vector_select_k.cc#L20

```
/Users/runner/work/crossbow/crossbow/arrow/cpp/src/arrow/compute/kernels/vector_select_k.cc:20:10: fatal error: 'ranges' file not found
   20 | #include <ranges>
      |          ^~~~~~~~
1 error generated.
```

From `test-r-macos-as-cran` nightly run: https://github.com/ursacomputing/crossbow/actions/runs/28413608596

Also failing on `test-r-wasm`: https://github.com/ursacomputing/crossbow/actions/runs/28413609309

Introduced in PR #46926 (merged Jun 22). Breaking `test-r-macos-as-cran` and `test-r-wasm` nightlies since June 23.

**Comment by raulcd** [comment]
@thisisnic the feature freeze is planned for today. This is a blocker, right? I can merge it after the feature freeze but I want to mark blockers so I don't create a Release Candidate until those are solved.

**Comment by thisisnic** [comment]
Yeah, mark as blocker please!

**Comment by thisisnic** [comment]
Issue resolved by pull request 50297
https://github.com/apache/arrow/pull/50297
