### PR TITLE
ARROW-7725: [C++] Add infrastructure for unity builds and precompiled headers

### PR DESCRIPTION
**Pull request by pitrou**
Unity builds and precompiled headers can be enabled "easily" in CMake 3.16:
https://cmake.org/cmake/help/v3.16/prop_tgt/UNITY_BUILD.html
https://cmake.org/cmake/help/v3.16/command/target_precompile_headers.html

They can make builds faster in some conditions, especially on CI with little parallelism and caching.

Some care is required to make them work:

- unity builds concatenate a number of C/C++ source files together,
  so there should be no symbol clashes, C++ namespace resolution issues
  or conflicting preprocessor definitions

- precompiled headers require that the same compile options are passed
  for all files using the header

### CODE REVIEW

**Comment by pitrou** [comment]
Example GHA normal build:
https://github.com/apache/arrow/runs/417128878
Same build in unity mode => 5 minutes faster:
https://github.com/pitrou/arrow/runs/417253236

**Comment by kszucs** [comment]
> Example GHA normal build:
> https://github.com/apache/arrow/runs/417128878
> Same build in unity mode => 5 minutes faster:
Nice!
> https://github.com/pitrou/arrow/runs/417253236

File: cpp/cmake_modules/BuildUtils.cmake [hunk 1]
```diff
@@ -173,21 +191,26 @@ function(ADD_ARROW_LIB LIB_NAME)
...
+  if(USE_OBJLIB)
+    # Generate a single "objlib" from all C++ modules and link
     # that "objlib" into each library kind, to avoid compiling twice
     add_library(${LIB_NAME}_objlib OBJECT ${ARG_SOURCES})
     # Necessary to make static linking into other shared libraries work properly
     set_property(TARGET ${LIB_NAME}_objlib PROPERTY POSITION_INDEPENDENT_CODE 1)
     if(ARG_DEPENDENCIES)
       add_dependencies(${LIB_NAME}_objlib ${ARG_DEPENDENCIES})
     endif()
+    if(ARG_PRECOMPILED_HEADER_LIB AND ARROW_USE_PRECOMPILED_HEADERS)
```
Comment (kou) [inline cpp/cmake_modules/BuildUtils.cmake]: Could you remove `AND ARROW_USE_PRECOMPILED_HEADERS` because this is checked in `reuse_precompiled_header_lib`?

File: cpp/src/arrow/dataset/pch.h [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+// KIND, either express or implied.  See the License for the
+// specific language governing permissions and limitations
+// under the License.
+
+// Often-used headers, for precompiling.
+// If updating this header, please make sure you check compilation speed
+// before checking in.  Adding headers which are not used extremely often
+// may incur a slowdown, since it makes the precompiled header heavier to load.
+
+#include "arrow/dataset/dataset.h"
```
Comment (kou) [inline cpp/src/arrow/dataset/pch.h]: (This is not related to this change.)

If we use `#include "..."`, we should use relative path of the current directory:

```cpp
#include "dataset.h"
#include "scanner.h"
#include "../pch.h"
```

If we don't use relative path, we should use `#include <...>` style.

See also:
* https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html
* https://docs.microsoft.com/en-us/cpp/preprocessor/hash-include-directive-c-cpp?view=vs-2019

**Review by kou — COMMENTED** [review]
This is interesting.
I tried reviewing this but it seems that you don't clean up changes yet.
For example, you will want to update `// XXX unused?` comment in `cpp/src/arrow/dummy.cc`.

I'll review again once you clean up changes.

File: cpp/cmake_modules/BuildUtils.cmake (hunk 1 above)
Comment (pitrou) [reply cpp/cmake_modules/BuildUtils.cmake]: Will do.

**Comment by pitrou** [comment]
I removed unused stuff and addressed your review comments @kou.

A small benchmark, clang 9.0, ccache disabled, Ubuntu 18.04, debug build:
```
# !UNITY & !PCH
real	1m7,932s
user	12m14,896s
sys	0m35,349s

# !UNITY & PCH
real	0m59,173s
user	10m39,391s
sys	0m33,052s

# UNITY & !PCH
real	0m49,501s
user	8m22,581s
sys	0m22,592s

# UNITY & PCH
real	0m48,917s
user	7m34,525s
sys	0m21,088s
```

**Comment by pitrou** [comment]
AppVeyor build here: https://ci.appveyor.com/project/pitrou/arrow/builds/30748930

@kou Do you want to review this again?

File: cpp/src/parquet/column_reader.cc [hunk 3]
```diff
@@ -110,7 +110,7 @@ ReaderProperties default_reader_properties() {
 // SerializedPageReader deserializes Thrift metadata and pages that have been
 // assembled in a serialized stream for storing in a Parquet files
 
-static constexpr int16_t kNonPageOrdinal = static_cast<int16_t>(-1);
+// static constexpr int16_t kNonPageOrdinal = static_cast<int16_t>(-1);
```
Comment (kou) [inline cpp/src/parquet/column_reader.cc]: Can we remove this?

**Review by kou — APPROVED** [review]
+1
`ApacheSoftwareFoundation/arrow` on AppVeyor is failed. I re-run the build.

**Comment by kou** [comment]
Umm. Failed again.

Does this error relate to this change?

https://ci.appveyor.com/project/ApacheSoftwareFoundation/arrow/builds/30818324/job/ilu5bu0422bn2s5q#L1207

```text
C:/projects/arrow/cpp/src/parquet/arrow/schema.cc(265): error C2039: 'DecimalSize': is not a member of 'parquet::arrow::internal'
C:/projects/arrow/cpp/src/parquet/arrow/reader.cc(928): note: see declaration of 'parquet::arrow::internal'
C:/projects/arrow/cpp/src/parquet/arrow/schema.cc(265): error C3861: 'DecimalSize': identifier not found
```

**Comment by pitrou** [comment]
> Does this error relate to this change?

Yes, it does. As mentioned in the PR message, unity builds can lead to C++ namespace resolution issues. Let's say you have two different files:

```c++
// a.cpp

namespace arrow {
namespace io {
namespace internal {

void SomeFunction();
}
}
}
```

```c++
// b.cpp

namespace arrow {
namespace io {
using internal::OtherFunction;
}
}
```

If `b.cpp` is compiled separately, `internal::OtherFunction` can refer to `::arrow::internal::OtherFunction`. But if `a.cpp` and `b.cpp` are concatenated together, then `internal::OtherFunction` will refer to `::arrow::io::internal::OtherFunction` which may not exist.

File: cpp/src/parquet/column_reader.cc (hunk 3 above)
Comment (pitrou) [reply cpp/src/parquet/column_reader.cc]: Oops, forgot it. Thank you.

**Comment by kou** [comment]
+1
