### PR TITLE
GH-35136: [Go][FlightSQL] Support backends without `CreatePreparedStatement` implemented

### LINKED ISSUE #35136: [Go][FlightSQL] Allow non-prepared queries
### Describe the enhancement requested

Currently, all queries are prepared as the driver does not implement the `QueryerContext` interface. As a consequence all backends not supporting `CreatePreparedStatement` will fail and cannot be used with the driver.

Please implement `QueryerContext` to allow usage of the mentioned backends with the driver.

### Component(s)

FlightRPC, Go

### PR DESCRIPTION
**Pull request by srebhan**
Without this PR all backends that do not implement `CreatePreparedStatement` will error out as the `database/sql` framework tries to prepare/execute all queries if the `QueryerContext` is missing. See linked issue.
* Closes: #35136

### CODE REVIEW

File: go/arrow/flight/flightsql/driver/driver.go [hunk 1]
```diff
@@ -442,11 +442,54 @@ func (c *Connection) PrepareContext(ctx context.Context, query string) (driver.S
...
+	}
+
+	info, err := c.client.Execute(ctx, query)
+	if err != nil {
+		return nil, err
+	}
+
+	rows := Rows{}
+	for _, endpoint := range info.Endpoint {
+		reader, err := c.client.DoGet(ctx, endpoint.GetTicket())
```
Comment (zeroshade) [inline go/arrow/flight/flightsql/driver/driver.go:474]: you need `defer reader.Release()`

Comment (srebhan) [reply go/arrow/flight/flightsql/driver/driver.go]: Refactored the code a bit as `func (s *Stmt) QueryContext(ctx context.Context, args []driver.NamedValue) (driver.Rows, error)` had the same issue.

**Comment by srebhan** [comment]
@zeroshade can you reproduce the CI error for AMD64 Debian 11 Go 1.18? Works with upstream `go version go1.18.10 linux/amd64` on my machine. :-(

**Review by zeroshade — COMMENTED** [review]
Looks like the CI passed after your last update. Is there any way you can add a test for this? :smile:

Otherwise it LGTM

**Review by zeroshade — APPROVED** [review]
LGTM i'll merge once CI passes
