### ISSUE TITLE
[GLib] Can't build with GLib 2.56

### ISSUE THREAD

**Issue by kou** [apache/arrow#39841]
### Describe the bug, including details regarding any error messages, version, and platform.

CentOS 7 and AlmaLinux 8 still use GLib 2.56:

CentOS 7:

https://github.com/ursacomputing/crossbow/actions/runs/7693204026/job/20961493252#step:8:4158

```text
FAILED: arrow-glib/libarrow-glib.so.1600.0.0.p/basic-data-type.cpp.o 
ccache c++ -Iarrow-glib/libarrow-glib.so.1600.0.0.p -I. -I.. -I../../cpp/build/src -I../../cpp/src -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++17 -g -Wmissing-declarations -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fPIC -MD -MQ arrow-glib/libarrow-glib.so.1600.0.0.p/basic-data-type.cpp.o -MF arrow-glib/libarrow-glib.so.1600.0.0.p/basic-data-type.cpp.o.d -o arrow-glib/libarrow-glib.so.1600.0.0.p/basic-data-type.cpp.o -c ../arrow-glib/basic-data-type.cpp
../arrow-glib/basic-data-type.cpp: In function 'GArrowTimestampDataType* garrow_timestamp_data_type_new(GArrowTimeUnit, GTimeZone*)':
../arrow-glib/basic-data-type.cpp:1230:22: error: 'g_time_zone_get_identifier' was not declared in this scope; did you mean 'g_time_zone_get_type'?
 1230 |     arrow_timezone = g_time_zone_get_identifier(time_zone);
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |                      g_time_zone_get_type
```

AlmaLinux 8:

https://github.com/ursacomputing/crossbow/actions/runs/7693204311/job/20961525718#step:8:4246

```text
FAILED: arrow-glib/libarrow-glib.so.1600.0.0.p/basic-data-type.cpp.o 
ccache c++ -Iarrow-glib/libarrow-glib.so.1600.0.0.p -I. -I.. -I../../cpp/build/src -I../../cpp/src -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c++17 -O0 -g -Wmissing-declarations -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -MD -MQ arrow-glib/libarrow-glib.so.1600.0.0.p/basic-data-type.cpp.o -MF arrow-glib/libarrow-glib.so.1600.0.0.p/basic-data-type.cpp.o.d -o arrow-glib/libarrow-glib.so.1600.0.0.p/basic-data-type.cpp.o -c ../arrow-glib/basic-data-type.cpp
../arrow-glib/basic-data-type.cpp: In function ‘GArrowTimestampDataType* garrow_timestamp_data_type_new(GArrowTimeUnit, GTimeZone*)’:
../arrow-glib/basic-data-type.cpp:1230:22: error: ‘g_time_zone_get_identifier’ was not declared in this scope
     arrow_timezone = g_time_zone_get_identifier(time_zone);
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~
../arrow-glib/basic-data-type.cpp:1230:22: note: suggested alternative: ‘g_time_zone_get_type’
     arrow_timezone = g_time_zone_get_identifier(time_zone);
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~
                      g_time_zone_get_type
```

### Component(s)

GLib
