### ISSUE TITLE
[C++][Benchmarking] Can't build with Google Benchmark 1.8.0

### ISSUE THREAD

**Issue by kou** [apache/arrow#35458]
### Describe the enhancement requested

https://github.com/apache/arrow/actions/runs/4897907287/jobs/8746494685?pr=35454#step:6:1881

```text
 In file included from /arrow/cpp/src/arrow/builder_benchmark.cc:32:
/arrow/cpp/src/arrow/util/benchmark_util.h:150:8: error: 'void arrow::MemoryPoolMemoryManager::Stop(benchmark::MemoryManager::Result*)' marked 'override', but does not override
  150 |   void Stop(benchmark::MemoryManager::Result* result) override {
      |        ^~~~
/arrow/cpp/src/arrow/util/benchmark_util.h:201:36: error: cannot declare field 'arrow::BenchmarkMemoryTracker::manager_' to be of abstract type 'arrow::MemoryPoolMemoryManager'
  201 |   ::arrow::MemoryPoolMemoryManager manager_;
      |                                    ^~~~~~~~
/arrow/cpp/src/arrow/util/benchmark_util.h:142:7: note:   because the following virtual functions are pure within 'arrow::MemoryPoolMemoryManager':
  142 | class MemoryPoolMemoryManager : public benchmark::MemoryManager {
      |       ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /arrow/cpp/src/arrow/builder_benchmark.cc:27:
/opt/conda/envs/arrow/include/benchmark/benchmark.h:408:16: note:     'virtual void benchmark::MemoryManager::Stop(benchmark::MemoryManager::Result&)'
  408 |   virtual void Stop(Result& result) = 0;
      |                ^~~~
```

https://github.com/google/benchmark/commit/9714eb8d118ff75da1f887f41645f7c4fab3e58f is related.

### Component(s)

Benchmarking, C++
