### PR TITLE
GH-35073: [R] Minimal build is failing (acero symbol not defined) 

### LINKED ISSUE #35073: [R] Minimal build is failing (acero symbol not defined)
### Describe the bug, including details regarding any error messages, version, and platform.

https://dev.azure.com/ursacomputing/crossbow/_build/results?buildId=47162&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=d9b15392-e4ce-5e4c-0c8c-b69645229181&l=1292

```
g++ -std=gnu++17 -I"/usr/share/R/include" -DNDEBUG -I/arrow/r/check/arrow.Rcheck/00_pkg_src/arrow/libarrow/arrow-11.0.0.9000/include -DARROW_STATIC   -I'/usr/local/lib/R/site-library/cpp11/include'    -fpic  -g -O2 -ffile-prefix-map=/build/r-base-4.2.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c arrowExports.cpp -o arrowExports.o
arrowExports.cpp:1053:57: error: ‘acero’ was not declared in this scope
 1053 | bool ExecNode_has_ordered_batches(const std::shared_ptr<acero::ExecNode>& node);
      |                                                         ^~~~~
arrowExports.cpp:1053:72: error: template argument 1 is invalid
 1053 | bool ExecNode_has_ordered_batches(const std::shared_ptr<acero::ExecNode>& node);
```

Maybe related to #34685 merging?

### Component(s)

R

### PR DESCRIPTION
**Pull request by thisisnic**
This PR updates the decorator in a function introduced in #34685 which inadvertently referenced `arrow` and not `acero`.
* Closes: #35073

### CODE REVIEW

**Comment by thisisnic** [comment]
@github-actions crossbow submit test-r-minimal-build

**Review by assignUser — APPROVED** [review]
+1
