### PR TITLE
GH-36730: [Python] Add support for Cython 3.0.0

### LINKED ISSUE #36730: [CI][Python] Cython 3.0 seems to make our build of pyarrow fail
### Describe the bug, including details regarding any error messages, version, and platform.

As seen on some jobs for 13.0.0 on the maintenance branch:
https://github.com/ursacomputing/crossbow/actions/runs/5576946887/jobs/10192099702
and this other branch from main:
https://github.com/ursacomputing/crossbow/actions/runs/5577773946/jobs/10191016009

It seems that the new version of Cython being used (it was released ~1 hour ago at the moment of creation of the issue):
```
 Collecting cython>=0.29.31 (from -r /Users/runner/work/crossbow/crossbow/arrow/python/requirements-wheel-build.txt (line 1))
  Obtaining dependency information for cython>=0.29.31 from https://files.pythonhosted.org/packages/a7/9d/643b508fc18fe095a8c1efea5bd86054ac63974ecd566dba962de40ebaa6/Cython-3.0.0-cp39-cp39-macosx_10_9_x86_64.whl.metadata
  Downloading Cython-3.0.0-cp39-cp39-macosx_10_9_x86_64.whl.metadata (3.1 kB)
```
There is a build issue:
```
 [15/129] cd /Users/runner/work/crossbow/crossbow/arrow/python/build/temp.macosx-10.14-x86_64-cpython-39 && /Users/runner/work/crossbow/crossbow/build-env/bin/python -m cython --cplus --warning-errors --directive embedsignature=True --working /Users/runner/work/crossbow/crossbow/arrow/python --output-file /Users/runner/work/crossbow/crossbow/arrow/python/build/temp.macosx-10.14-x86_64-cpython-39/_flight.cpp /Users/runner/work/crossbow/crossbow/arrow/python/pyarrow/_flight.pyx
FAILED: CMakeFiles/_flight_pyx /Users/runner/work/crossbow/crossbow/arrow/python/build/temp.macosx-10.14-x86_64-cpython-39/CMakeFiles/_flight_pyx 
cd /Users/runner/work/crossbow/crossbow/arrow/python/build/temp.macosx-10.14-x86_64-cpython-39 && /Users/runner/work/crossbow/crossbow/build-env/bin/python -m cython --cplus --warning-errors --directive embedsignature=True --working /Users/runner/work/crossbow/crossbow/arrow/python --output-file /Users/runner/work/crossbow/crossbow/arrow/python/build/temp.macosx-10.14-x86_64-cpython-39/_flight.cpp /Users/runner/work/crossbow/crossbow/arrow/python/pyarrow/_flight.pyx

Error compiling Cython file:
------------------------------------------------------------
...

    cdef cppclass CFlightListing" arrow::flight::FlightListing":
        CResult[unique_ptr[CFlightInfo]] Next()

    cdef cppclass CSimpleFlightListing" arrow::flight::SimpleFlightListing":
        CSimpleFlightListing(vector[CFlightInfo]&& info)
                            ^
------------------------------------------------------------

pyarrow/includes/libarrow_flight.pxd:175:28: Rvalue-reference as function argument not supported

Error compiling Cython file:
------------------------------------------------------------
...
            # Text header values in gRPC (and HTTP/1, HTTP/2) are
            # required to be valid ASCII. Binary header values are
            # exposed as bytes.
            value = value.decode("ascii")
        headers.setdefault(header, []).append(value)
        postincrement(header_iter)
        ^
------------------------------------------------------------

pyarrow/_flight.pyx:2312:8: No 'operator++(int)' declared for postfix '++' (operand type is 'const_iterator')
```

### Component(s)

Continuous Integration, Python

### PR DESCRIPTION
**Pull request by kou**
### Rationale for this change

Cython 3.0.0 is the latest release. PyArrow should work with Cython 3.0.0.

### What changes are included in this PR?

* Don't use `vector[XXX]&&`
* Add a declaration for `postincrement`
  * See also: https://cython.readthedocs.io/en/latest/src/userguide/migrating_to_cy30.html#c-postincrement-postdecrement-operator
* Ignore `C4551` warning (function call missing argument list) with MSVC
  * See also: https://github.com/cython/cython/issues/4445
* Add missing `const` to `CLocation`'s static methods.
* Don't use `StopIteration` to stop generator
  * See also: https://cython.readthedocs.io/en/latest/src/userguide/migrating_to_cy30.html#python-3-syntax-semantics

### Are these changes tested?

Yes.

### Are there any user-facing changes?

Yes.
* Closes: #36730

### CODE REVIEW

**Comment by pitrou** [comment]
This may fix the compilation error but there are other issues during tests (see macOS CI?).

**Comment by kou** [comment]
I've fixed CI failures.

**Comment by jorisvandenbossche** [comment]
@kou there were also some runtime errors in the minimal build that are caused by cython 3. Based on your diff, I don't think that will already be fixed here, but let me run them to be sure.

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow submit example-python-minimal-build-fedora-conda

**Comment by pitrou** [comment]
@github-actions crossbow -g python

**Comment by pitrou** [comment]
Can this PR also undo the pinning on various Python builds?

**Comment by kou** [comment]
@github-actions crossbow submit example-python-minimal-build-fedora-conda

**Comment by kou** [comment]
I've fixed the generator related problem.
I'll rebase on main and unpin Cython version.

**Comment by kou** [comment]
Hmm. Can we detect Cython version in `.{pyx,pxi}`?

**Comment by pitrou** [comment]
There should not be any need to raise  `StopIteration`.

File: python/pyarrow/ipc.pxi [hunk 1]
```diff
@@ -437,7 +437,11 @@ cdef class MessageReader(_Weakrefable):
 
     def __iter__(self):
         while True:
-            yield self.read_next_message()
+            try:
+                yield self.read_next_message()
+            except StopIteration:
+                # For Cython >= 3.0.0
+                return
```
Comment (jorisvandenbossche) [inline python/pyarrow/ipc.pxi:444]: I don't know if it is this code that gives problems to be written in a way that works for both cython 0.29 and 3, but a potential different way of writing it:

```
def __iter__(self):
    return self

def __next__(self):
    return self.read_next_message()
```

Comment (kou) [reply python/pyarrow/ipc.pxi]: Thanks! I'll try it.

File: python/pyarrow/scalar.pxi [hunk 2]
```diff
@@ -793,7 +793,7 @@ cdef class MapScalar(ListScalar):
         """
         arr = self.values
         if array is None:
```
Comment (jorisvandenbossche) [inline python/pyarrow/scalar.pxi:795]: Not related to this PR, but just noticing: this line uses `array` variable, but that is not defined in this scope (only `arr` is), so this `array` variable is actually referring to the `pyarrow.lib.array(..)` function ..

Comment (kou) [reply python/pyarrow/scalar.pxi]: I think so too now. :-)
I've renamed it to `ary`.

File: python/pyarrow/scalar.pxi [hunk 3]
```diff
@@ -791,8 +791,11 @@ cdef class MapScalar(ListScalar):
...
         """
+        return self
+
+    def __next__(self):
         arr = self.values
-        if array is None:
+        if arr is None:
             raise StopIteration
         for k, v in zip(arr.field('key'), arr.field('value')):
             yield (k.as_py(), v.as_py())
```
Comment (pitrou) [inline python/pyarrow/scalar.pxi:801]: Do you actually test these changes before pushing them?

You can't use `yield` in a `__next__` function.
Either you write `__iter__` as a generator (using `yield`), or you write a pair of `__iter__` and `__next__` functions (without `yield`). You can't mix the two styles.

Comment (jorisvandenbossche) [reply python/pyarrow/scalar.pxi:801]: And FWIW, for this case, I would leave the `__iter__` as is (in the other cases such as RecordBatchReader, we already have a public "next" method that can just be called from `__next__`)

**Review by lidavidm — APPROVED** [review]
Flight changes LGTM, thanks!

File: python/pyarrow/scalar.pxi (hunk 3 above)
Comment (kou) [reply python/pyarrow/scalar.pxi:798]: Sorry. I didn't test on local before I pushed a commit because I don't have enough time yesterday.

I reverted the `__iter__` + `__next__` change.

**Comment by kou** [comment]
@jorisvandenbossche Do you have any idea why the following failure was happen?

https://github.com/apache/arrow/actions/runs/5615711782/job/15216554355?pr=36745#step:6:6074

```text
 =================================== FAILURES ===================================
_______________________ test_cloudpickle_dataset[False] ________________________

tempdir = PosixPath('/tmp/pytest-of-root/pytest-0/test_cloudpickle_dataset_False0')
datadir = PosixPath('/opt/conda/envs/arrow/lib/python3.8/site-packages/pyarrow/tests/data/parquet')
use_legacy_dataset = False

    @pytest.mark.pandas
    @parametrize_legacy_dataset
    def test_cloudpickle_dataset(tempdir, datadir, use_legacy_dataset):
        cp = pytest.importorskip('cloudpickle')
        dataset = _make_dataset_for_pickling(tempdir, use_legacy_dataset)
>       _assert_dataset_is_picklable(
            dataset, pickler=cp, use_legacy_dataset=use_legacy_dataset)

opt/conda/envs/arrow/lib/python3.8/site-packages/pyarrow/tests/parquet/test_dataset.py:1572: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
opt/conda/envs/arrow/lib/python3.8/site-packages/pyarrow/tests/parquet/test_dataset.py:1540: in _assert_dataset_is_picklable
    assert is_pickleable(dataset)
opt/conda/envs/arrow/lib/python3.8/site-packages/pyarrow/tests/parquet/test_dataset.py:1538: in is_pickleable
    return obj == pickler.loads(pickler.dumps(obj))
opt/conda/envs/arrow/lib/python3.8/site-packages/cloudpickle/cloudpickle_fast.py:73: in dumps
    cp.dump(obj)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <cloudpickle.cloudpickle_fast.CloudPickler object at 0x7f25aa27aa10>
obj = <pyarrow.parquet.core._ParquetDatasetV2 object at 0x7f25a9ec9690>

    def dump(self, obj):
        try:
>           return Pickler.dump(self, obj)
E           _pickle.PicklingError: Can't pickle <cyfunction ParquetFragmentScanOptions._reconstruct at 0x7f2660177140>: it's not the same object as pyarrow._dataset_parquet.ParquetFragmentScanOptions._reconstruct

opt/conda/envs/arrow/lib/python3.8/site-packages/cloudpickle/cloudpickle_fast.py:632: PicklingError
```

**Comment by jorisvandenbossche** [comment]
Not directly an idea. We use the same pattern in many other places. Can you try this patch:

```diff
--- a/python/pyarrow/_dataset_parquet.pyx
+++ b/python/pyarrow/_dataset_parquet.pyx
@@ -741,7 +741,7 @@ cdef class ParquetFragmentScanOptions(FragmentScanOptions):
             thrift_string_size_limit=self.thrift_string_size_limit,
             thrift_container_size_limit=self.thrift_container_size_limit,
         )
-        return type(self)._reconstruct, (kwargs,)
+        return ParquetFragmentScanOptions._reconstruct, (kwargs,)
```

(in theory it shouldn't matter for python, but maybe cython 3 has a bug that treats this different)

**Comment by kou** [comment]
Thanks! I've pushed your patch.

**Comment by h-vetinari** [comment]
If there are problems with compatibility between 0.29 and 3.0 (aside from the few intentional breaking changes), the Cython devs are usually quick to respond if you open an [issue](https://github.com/cython/cython/issues)

**Comment by danepitkin** [comment]
The failing pickle test is only when using the `cloudpickle` module instead of the python pickle module. Perhaps they don't support cython3.0.0 yet? This is the only test in the entire codebase that tests cloudpickle.. not sure how important it is as a dependency to pyarrow.

```
@pytest.mark.pandas
@parametrize_legacy_dataset
def test_cloudpickle_dataset(tempdir, datadir, use_legacy_dataset):
    cp = pytest.importorskip('cloudpickle')
    dataset = _make_dataset_for_pickling(tempdir, use_legacy_dataset)
    _assert_dataset_is_picklable(
        dataset, pickler=cp, use_legacy_dataset=use_legacy_dataset)
```

**Comment by pitrou** [comment]
Well, first, this PR should be rebased, because there are conflicts.

**Comment by danepitkin** [comment]
I did rebase/squash here to test things out here: https://github.com/apache/arrow/pull/37097

I wanted to experiment without polluting this PR. I can merge any fixes I find back into this PR.

**Comment by kou** [comment]
Can we use #37097 instead of this?

**Comment by danepitkin** [comment]
> Can we use #37097 instead of this?

Sure!

**Comment by kou** [comment]
I close this in favor of #37097.
