### ISSUE TITLE
[Packaging][RPM] almalinux-8/centos-8-stream jobs failed to build google-cloud-cpp

### ISSUE THREAD

**Issue by kou** [apache/arrow#43158]
### Describe the bug, including details regarding any error messages, version, and platform.

This is introduced by #43136.

https://github.com/ursacomputing/crossbow/actions/runs/9813967777/job/27100880520#step:8:3220

```text
-- stderr output is:
In file included from /root/rpmbuild/BUILD/apache-arrow-17.0.0.dev448/cpp/build/google_cloud_cpp_ep-prefix/src/google_cloud_cpp_ep/google/cloud/internal/oauth2_authorized_user_credentials.cc:16:
/root/rpmbuild/BUILD/apache-arrow-17.0.0.dev448/cpp/build/google_cloud_cpp_ep-prefix/src/google_cloud_cpp_ep/google/cloud/internal/oauth2_universe_domain.h:22:10: fatal error: nlohmann/json_fwd.hpp: No such file or directory
 #include <nlohmann/json_fwd.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

It's the cause that google-cloud-cpp requires nlohmann/json is installed with `-DJSON_MultipleHeaders=ON` but `json-devel` on AlmaLinux 8/CentOS Stream 8 isn't.

The upstream issue: https://github.com/googleapis/google-cloud-cpp/issues/14438

### Component(s)

Packaging

**Comment by kou** [comment]
Issue resolved by pull request 43159
https://github.com/apache/arrow/pull/43159
