### PR TITLE
GH-33649: [C++] Fix documentation on Newly Added Methods on ExecPlan

### LINKED ISSUE #33649: [C++] Fix documentation on Newly Added Methods on ExecPlan
### Describe the bug, including details regarding any error messages, version, and platform.

We see the following error in the CIs : https://github.com/apache/arrow/pull/33623#issuecomment-1381326714

```bash
/arrow/cpp/src/arrow/compute/exec/exec_plan.h:427: error: The following parameter of arrow::compute::DeclarationToTable(Declaration declaration, bool use_threads=true, MemoryPool *memory_pool=default_memory_pool(), FunctionRegistry *function_registry=NULLPTR) is not documented:
  parameter 'declaration' (warning treated as error, aborting now)
```

### Component(s)

C++

### PR DESCRIPTION
**Pull request by vibhatha**
This is a minor fix for CI failure in https://github.com/apache/arrow/pull/33623#issuecomment-1381326714. 

**TODO**

- [x] Self review
- [x] Check for CI status
- [x] Mark PR ready for review

* Closes: #33649

### CODE REVIEW

**Comment by westonpace** [comment]
Ah, sorry, I did not see this when I logged on this morning and I fixed this on my existing docs PR.

https://github.com/apache/arrow/commit/22136989ab28954bb3ad42514fbd130848b2fc0d

Can you review my wording?  If it's ok we can probably close this.

**Comment by vibhatha** [comment]
closing this PR in favor of https://github.com/apache/arrow/commit/22136989ab28954bb3ad42514fbd130848b2fc0d

**Comment by vibhatha** [comment]
> Ah, sorry, I did not see this when I logged on this morning and I fixed this on my existing docs PR.
> 
> [2213698](https://github.com/apache/arrow/commit/22136989ab28954bb3ad42514fbd130848b2fc0d)
> 
> Can you review my wording? If it's ok we can probably close this.

Sorry I wasn't online at that time. And I see the PR is merged, the wording is fine. Since, I am closing this one.
