### PR TITLE
GH-50542: [C++] Fix ARROW_SIMD_LEVEL=NONE build, compile SSE4.2 kernels

### PR DESCRIPTION
**Pull request by domibel**
### Rationale for this change

Building with ARROW_SIMD_LEVEL=NONE and ARROW_RUNTIME_SIMD_LEVEL=MAX failed with:

  bpacking.cc:39:49: error: 'unpack_sse4_2' is not a member of
  'arrow::internal::bpacking'

The SSE4.2 dispatch table entries are emitted when either the compile-time or the runtime macro is set, but the kernels themselves were only compiled when the compile-time macro was set.

### What changes are included in this PR?

I moved the byte_stream_split SSE4.2 instantiations into a dedicated translation unit, keeping the dispatcher's own unit at the baseline ISA.

### Are these changes tested?

Yes

### Are there any user-facing changes?

No

* GitHub Issue: #50542

### CODE REVIEW

**Comment by AntoinePrv** [comment]
The PR looks sensible but this may not be the only limitation. From what I understood when last working on this part of the code, SSE4.2 is mandatory when building Arrow C++.
I believe the reason at the time was the unconditional usage of `popcnt`, but perhaps now that we moved to `std::popcnt` this is more portable.
There may be more places in the CMakeLists.txt where the default compiler options do pick a minimal SSE4.2 baseline so that would be a place to look at as well.

In principle I think treating all SIMD as optional makes the code more uniform, and is a free abstraction since the dispatch will change to static when possible.

@domibel I'm curious what is your use case? Do you only wish to disable SIMD, or do you need to target below SSE4.2?

**Comment by domibel** [comment]
@AntoinePrv Debian is using the x86-64-v1 baseline, so we build with ARROW_SIMD_LEVEL=NONE but keep ARROW_RUNTIME_SIMD_LEVEL=MAX for dispatching at runtime. That means we don't disable SIMD, we just keep it out of the baseline. The PR is fixing a regression introduced somewhere after the 23 release.

@kou Could ARROW_SIMD_LEVEL=NONE be added to the nightly test coverage?

**Comment by kou** [comment]
Yes. Could you add it to https://github.com/apache/arrow/blob/main/.github/workflows/cpp_extra.yml#L96-L124 ?

File: .github/workflows/cpp_extra.yml [hunk 1]
```diff
@@ -122,6 +122,13 @@ jobs:
               -e CMAKE_CXX_STANDARD=23
             runs-on: ubuntu-latest
             title: AMD64 Debian C++23
+          - envs:
+              - DEBIAN=13
+            image: debian-cpp
+            run-options: >-
+              -e ARROW_SIMD_LEVEL=NONE
```
Comment (AntoinePrv) [inline .github/workflows/cpp_extra.yml:127]: Can you try adding somethin explicit like
```
CMAKE_CXX_FLAGS=-march=x86-64
```

File: cpp/src/arrow/util/byte_stream_split_internal.h
Comment (pitrou) [inline cpp/src/arrow/util/byte_stream_split_internal.h]: Move this comment above the SSE4.2 block?

Comment (domibel) [reply cpp/src/arrow/util/byte_stream_split_internal.h]: good catch, done

File: .github/workflows/cpp_extra.yml (hunk 1 above)
Comment (domibel) [reply .github/workflows/cpp_extra.yml:127]: That makes sense, I added CXXFLAGS

**Comment by domibel** [comment]
Is there anything else I can help with to get this merged?

File: .github/workflows/cpp_extra.yml [hunk 2]
```diff
@@ -122,6 +122,14 @@ jobs:
               -e CMAKE_CXX_STANDARD=23
             runs-on: ubuntu-latest
             title: AMD64 Debian C++23
+          - envs:
+              - DEBIAN=13
```
Comment (kou) [inline .github/workflows/cpp_extra.yml]: Can we remove explicit `DEBIAN=13`?

File: .github/workflows/cpp_extra.yml [hunk 3]
```diff
@@ -122,6 +122,14 @@ jobs:
...
+            image: debian-cpp
+            run-options: >-
+              -e ARROW_SIMD_LEVEL=NONE
+              -e CXXFLAGS=-march=x86-64
```
Comment (kou) [inline .github/workflows/cpp_extra.yml]: Could you use `ARROW_CXXFLAGS` instead? `ARROW_CXXFLAGS` just appends flags to `CMAKE_CXX_FLAGS` instead of overriding it.

File: .github/workflows/cpp_extra.yml (hunk 2 above)
Comment (domibel) [reply .github/workflows/cpp_extra.yml]: Sure, I followed the example above which also carry the same lines (lines 118-119 ).

**Review by kou — APPROVED** [review]
+1
