### ISSUE TITLE
[C++] Arrow 12 cpp doesn't compile with protobuf 23.0 

### ISSUE THREAD

**Issue by smahapatra1** [apache/arrow#35538]
### Describe the bug, including details regarding any error messages, version, and platform.

cpp/src/arrow/engine/substrait/serde.cc:27:10: fatal error: google/protobuf/stubs/status.h: No such file or directory
   27 | #include <google/protobuf/stubs/status.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

### Component(s)

C++, FlightRPC

**Comment by westonpace** [comment]
Issue resolved by pull request 35673
https://github.com/apache/arrow/pull/35673
